(deftheme afternoon
  "Created 2014-07-08.")

(custom-theme-set-variables
 'afternoon
 '(ansi-color-names-vector ["#eaeaea" "#d54e53" "DarkOliveGreen3" "#e7c547" "DeepSkyBlue1" "#c397d8" "#70c0b1" "#1c1c1c"])
 '(ansi-color-faces-vector [default bold shadow italic underline bold bold-italic bold]))

(custom-theme-set-faces
 'afternoon
 '(bold ((((class color) (min-colors 89)) (:weight bold))))
 '(bold-italic ((((class color) (min-colors 89)) (:slant italic :weight bold))))
 '(underline ((((class color) (min-colors 89)) (:underline t))))
 '(italic ((((class color) (min-colors 89)) (:slant italic))))
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "LightCoral"))))
 '(font-lock-comment-delimiter-face ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(font-lock-comment-face ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(font-lock-constant-face ((((class color) (min-colors 89)) (:foreground "DarkOliveGreen3"))))
 '(font-lock-doc-face ((((class color) (min-colors 89)) (:foreground "moccasin"))))
 '(font-lock-doc-string-face ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(font-lock-function-name-face ((((class color) (min-colors 89)) (:foreground "goldenrod"))))
 '(font-lock-keyword-face ((((class color) (min-colors 89)) (:foreground "DeepSkyBlue1"))))
 '(font-lock-negation-char-face ((((class color) (min-colors 89)) (:foreground "DeepSkyBlue1"))))
 '(font-lock-preprocessor-face ((((class color) (min-colors 89)) (:foreground "gold"))))
 '(font-lock-regexp-grouping-backslash ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(font-lock-regexp-grouping-construct ((((class color) (min-colors 89)) (:foreground "#c397d8"))))
 '(font-lock-string-face ((((class color) (min-colors 89)) (:foreground "burlywood"))))
 '(font-lock-type-face ((((class color) (min-colors 89)) (:foreground "CadetBlue1"))))
 '(font-lock-variable-name-face ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(font-lock-warning-face ((((class color) (min-colors 89)) (:weight bold :foreground "#d54e53"))))
 '(shadow ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(success ((((class color) (min-colors 89)) (:foreground "SeaGreen2"))))
 '(error ((((class color) (min-colors 89)) (:foreground "#d54e53"))))
 '(warning ((((class color) (min-colors 89)) (:foreground "goldenrod"))))
 '(flycheck-error ((((class color) (min-colors 89)) (:underline (:style wave :color "#d54e53")))))
 '(flycheck-warning ((((class color) (min-colors 89)) (:underline (:style wave :color "goldenrod")))))
 '(flymake-warnline ((((class color) (min-colors 89)) (:underline (:style wave :color "goldenrod") :background "#1c1c1c"))))
 '(flymake-errline ((((class color) (min-colors 89)) (:underline (:style wave :color "#d54e53") :background "#1c1c1c"))))
 '(clojure-test-failure-face ((((class color) (min-colors 89)) (:background nil :inherit flymake-warnline))))
 '(clojure-test-error-face ((((class color) (min-colors 89)) (:background nil :inherit flymake-errline))))
 '(clojure-test-success-face ((((class color) (min-colors 89)) (:background nil :foreground nil :underline "DarkOliveGreen3"))))
 '(edts-face-warning-line ((t (:background nil :inherit flymake-warnline))))
 '(edts-face-warning-mode-line ((((class color) (min-colors 89)) (:background nil :foreground "goldenrod" :weight bold))))
 '(edts-face-error-line ((t (:background nil :inherit flymake-errline))))
 '(edts-face-error-mode-line ((((class color) (min-colors 89)) (:background nil :foreground "#d54e53" :weight bold))))
 '(clojure-keyword ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(clojure-parens ((((class color) (min-colors 89)) (:foreground "#eaeaea"))))
 '(clojure-braces ((((class color) (min-colors 89)) (:foreground "DarkOliveGreen3"))))
 '(clojure-brackets ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(clojure-double-quote ((((class color) (min-colors 89)) (:foreground "#70c0b1" :background nil))))
 '(clojure-special ((((class color) (min-colors 89)) (:foreground "DeepSkyBlue1"))))
 '(clojure-java-call ((((class color) (min-colors 89)) (:foreground "#c397d8"))))
 '(rainbow-delimiters-depth-1-face ((((class color) (min-colors 89)) (:foreground "#eaeaea"))))
 '(rainbow-delimiters-depth-2-face ((((class color) (min-colors 89)) (:foreground "#70c0b1"))))
 '(rainbow-delimiters-depth-3-face ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(rainbow-delimiters-depth-4-face ((((class color) (min-colors 89)) (:foreground "DarkOliveGreen3"))))
 '(rainbow-delimiters-depth-5-face ((((class color) (min-colors 89)) (:foreground "DeepSkyBlue1"))))
 '(rainbow-delimiters-depth-6-face ((((class color) (min-colors 89)) (:foreground "#eaeaea"))))
 '(rainbow-delimiters-depth-7-face ((((class color) (min-colors 89)) (:foreground "#70c0b1"))))
 '(rainbow-delimiters-depth-8-face ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(rainbow-delimiters-depth-9-face ((((class color) (min-colors 89)) (:foreground "DarkOliveGreen3"))))
 '(rainbow-delimiters-unmatched-face ((((class color) (min-colors 89)) (:foreground "#d54e53"))))
 '(mmm-code-submode-face ((((class color) (min-colors 89)) (:background "#121212"))))
 '(mmm-comment-submode-face ((((class color) (min-colors 89)) (:inherit font-lock-comment-face))))
 '(mmm-output-submode-face ((((class color) (min-colors 89)) (:background "#121212"))))
 '(match ((((class color) (min-colors 89)) (:foreground "DeepSkyBlue1" :background "#1c1c1c" :inverse-video t))))
 '(isearch ((((class color) (min-colors 89)) (:foreground "#e7c547" :background "#1c1c1c" :inverse-video t))))
 '(lazy-highlight ((((class color) (min-colors 89)) (:foreground "#70c0b1" :background "#1c1c1c" :inverse-video t))))
 '(isearch-fail ((((class color) (min-colors 89)) (:background "#1c1c1c" :inherit font-lock-warning-face :inverse-video t))))
 '(anzu-mode-line ((((class color) (min-colors 89)) (:foreground "goldenrod"))))
 '(anzu-replace-highlight ((((class color) (min-colors 89)) (:inherit isearch-lazy-highlight-face))))
 '(anzu-replace-to ((((class color) (min-colors 89)) (:inherit isearch))))
 '(ido-subdir ((((class color) (min-colors 89)) (:foreground "#c397d8"))))
 '(ido-first-match ((((class color) (min-colors 89)) (:foreground "goldenrod"))))
 '(ido-only-match ((((class color) (min-colors 89)) (:foreground "DarkOliveGreen3"))))
 '(ido-indicator ((((class color) (min-colors 89)) (:foreground "#d54e53" :background "#1c1c1c"))))
 '(ido-virtual ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(flx-highlight-face ((((class color) (min-colors 89)) (:inherit nil :foreground "#e7c547" :weight bold :underline nil))))
 '(which-func ((((class color) (min-colors 89)) (:foreground "DeepSkyBlue1" :background nil))))
 '(cursor ((((class color) (min-colors 89)) (:background "goldenrod"))))
 '(fringe ((((class color) (min-colors 89)) (:background "#121212"))))
 '(linum ((((class color) (min-colors 89)) (:background "#121212" :foreground "DarkOliveGreen3"))))
 '(border ((((class color) (min-colors 89)) (:background "#121212"))))
 '(border-glyph ((((class color) (min-colors 89)) (nil))))
 '(highlight ((((class color) (min-colors 89)) (:inverse-video nil :background "#121212"))))
 '(gui-element ((((class color) (min-colors 89)) (:background "#121212" :foreground "#eaeaea"))))
 '(mode-line ((((class color) (min-colors 89)) (:foreground nil :background "#121212" :box (:line-width 1 :color "#eaeaea") :family "Lucida Grande"))))
 '(mode-line-buffer-id ((((class color) (min-colors 89)) (:foreground "#c397d8" :background nil))))
 '(mode-line-inactive ((((class color) (min-colors 89)) (:inherit mode-line :foreground "#969896" :background "#121212" :weight normal :box (:line-width 1 :color "#eaeaea")))))
 '(mode-line-emphasis ((((class color) (min-colors 89)) (:foreground "#eaeaea" :slant italic))))
 '(mode-line-highlight ((((class color) (min-colors 89)) (:foreground "#c397d8" :box nil))))
 '(minibuffer-prompt ((((class color) (min-colors 89)) (:foreground "DeepSkyBlue1"))))
 '(region ((((class color) (min-colors 89)) (:background "#103050"))))
 '(secondary-selection ((((class color) (min-colors 89)) (:background "#121212"))))
 '(header-line ((((class color) (min-colors 89)) (:inherit mode-line :foreground "#c397d8" :background nil))))
 '(trailing-whitespace ((((class color) (min-colors 89)) (:foreground "#d54e53" :inverse-video t :underline nil))))
 '(whitespace-trailing ((((class color) (min-colors 89)) (:foreground "#d54e53" :inverse-video t :underline nil))))
 '(whitespace-space-after-tab ((((class color) (min-colors 89)) (:foreground "#d54e53" :inverse-video t :underline nil))))
 '(whitespace-space-before-tab ((((class color) (min-colors 89)) (:foreground "#d54e53" :inverse-video t :underline nil))))
 '(whitespace-empty ((((class color) (min-colors 89)) (:foreground "#d54e53" :inverse-video t :underline nil))))
 '(whitespace-line ((((class color) (min-colors 89)) (:background nil :foreground "#d54e53"))))
 '(whitespace-indentation ((((class color) (min-colors 89)) (:background nil :foreground "#70c0b1"))))
 '(whitespace-space ((((class color) (min-colors 89)) (:background nil :foreground "#103050"))))
 '(whitespace-newline ((((class color) (min-colors 89)) (:background nil :foreground "#103050"))))
 '(whitespace-tab ((((class color) (min-colors 89)) (:background nil :foreground "#103050"))))
 '(whitespace-hspace ((((class color) (min-colors 89)) (:background nil :foreground "#103050"))))
 '(show-paren-match ((((class color) (min-colors 89)) (:background "dodgerblue1" :foreground "white"))))
 '(show-paren-mismatch ((((class color) (min-colors 89)) (:background "red1" :foreground "white"))))
 '(sp-show-pair-match-face ((((class color) (min-colors 89)) (:foreground nil :background nil :inherit show-paren-match))))
 '(sp-show-pair-mismatch-face ((((class color) (min-colors 89)) (:foreground nil :background nil :inherit show-paren-mismatch))))
 '(paren-face-match ((((class color) (min-colors 89)) (:foreground nil :background nil :inherit show-paren-match))))
 '(paren-face-mismatch ((((class color) (min-colors 89)) (:foreground nil :background nil :inherit show-paren-mismatch))))
 '(paren-face-no-match ((((class color) (min-colors 89)) (:foreground nil :background nil :inherit show-paren-mismatch))))
 '(paren-face ((((class color) (min-colors 89)) (:foreground "#969896" :background nil))))
 '(sh-heredoc ((((class color) (min-colors 89)) (:foreground nil :inherit font-lock-string-face :weight normal))))
 '(sh-quoted-exec ((((class color) (min-colors 89)) (:foreground nil :inherit font-lock-preprocessor-face))))
 '(slime-highlight-edits-face ((((class color) (min-colors 89)) (:weight bold))))
 '(slime-repl-input-face ((((class color) (min-colors 89)) (:weight normal :underline nil))))
 '(slime-repl-prompt-face ((((class color) (min-colors 89)) (:underline nil :weight bold :foreground "#c397d8"))))
 '(slime-repl-result-face ((((class color) (min-colors 89)) (:foreground "DarkOliveGreen3"))))
 '(slime-repl-output-face ((((class color) (min-colors 89)) (:foreground "DeepSkyBlue1" :background "#1c1c1c"))))
 '(csv-separator-face ((((class color) (min-colors 89)) (:foreground "goldenrod"))))
 '(diff-added ((((class color) (min-colors 89)) (:foreground "DarkOliveGreen3"))))
 '(diff-changed ((((class color) (min-colors 89)) (:foreground "#c397d8"))))
 '(diff-removed ((((class color) (min-colors 89)) (:foreground "goldenrod"))))
 '(diff-header ((((class color) (min-colors 89)) (:foreground "#70c0b1" :background nil))))
 '(diff-file-header ((((class color) (min-colors 89)) (:foreground "DeepSkyBlue1" :background nil))))
 '(diff-hunk-header ((((class color) (min-colors 89)) (:foreground "#c397d8"))))
 '(diff-refine-added ((((class color) (min-colors 89)) (:inherit diff-added :inverse-video t))))
 '(diff-refine-removed ((((class color) (min-colors 89)) (:inherit diff-removed :inverse-video t))))
 '(ediff-even-diff-A ((((class color) (min-colors 89)) (:foreground nil :background nil :inverse-video t))))
 '(ediff-even-diff-B ((((class color) (min-colors 89)) (:foreground nil :background nil :inverse-video t))))
 '(ediff-odd-diff-A ((((class color) (min-colors 89)) (:foreground "#969896" :background nil :inverse-video t))))
 '(ediff-odd-diff-B ((((class color) (min-colors 89)) (:foreground "#969896" :background nil :inverse-video t))))
 '(eldoc-highlight-function-argument ((((class color) (min-colors 89)) (:foreground "DarkOliveGreen3" :weight bold))))
 '(macrostep-expansion-highlight-face ((((class color) (min-colors 89)) (:inherit highlight :foreground nil))))
 '(undo-tree-visualizer-default-face ((((class color) (min-colors 89)) (:foreground "#eaeaea"))))
 '(undo-tree-visualizer-current-face ((((class color) (min-colors 89)) (:foreground "DarkOliveGreen3" :weight bold))))
 '(undo-tree-visualizer-active-branch-face ((((class color) (min-colors 89)) (:foreground "#d54e53"))))
 '(undo-tree-visualizer-register-face ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(diredp-compressed-file-suffix ((((class color) (min-colors 89)) (:foreground "DeepSkyBlue1"))))
 '(diredp-deletion ((((class color) (min-colors 89)) (:inherit error :inverse-video t))))
 '(diredp-deletion-file-name ((((class color) (min-colors 89)) (:inherit error))))
 '(diredp-dir-heading ((((class color) (min-colors 89)) (:foreground "DarkOliveGreen3" :weight bold))))
 '(diredp-dir-priv ((((class color) (min-colors 89)) (:foreground "#70c0b1" :background nil))))
 '(diredp-exec-priv ((((class color) (min-colors 89)) (:foreground "DeepSkyBlue1" :background nil))))
 '(diredp-executable-tag ((((class color) (min-colors 89)) (:foreground "#d54e53" :background nil))))
 '(diredp-file-name ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(diredp-file-suffix ((((class color) (min-colors 89)) (:foreground "DarkOliveGreen3"))))
 '(diredp-flag-mark ((((class color) (min-colors 89)) (:foreground "DarkOliveGreen3" :inverse-video t))))
 '(diredp-flag-mark-line ((((class color) (min-colors 89)) (:background nil :inherit highlight))))
 '(diredp-ignored-file-name ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(diredp-link-priv ((((class color) (min-colors 89)) (:background nil :foreground "#c397d8"))))
 '(diredp-mode-line-flagged ((((class color) (min-colors 89)) (:foreground "#d54e53"))))
 '(diredp-mode-line-marked ((((class color) (min-colors 89)) (:foreground "DarkOliveGreen3"))))
 '(diredp-no-priv ((((class color) (min-colors 89)) (:background nil))))
 '(diredp-number ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(diredp-other-priv ((((class color) (min-colors 89)) (:background nil :foreground "#c397d8"))))
 '(diredp-rare-priv ((((class color) (min-colors 89)) (:foreground "#d54e53" :background nil))))
 '(diredp-read-priv ((((class color) (min-colors 89)) (:foreground "DarkOliveGreen3" :background nil))))
 '(diredp-symlink ((((class color) (min-colors 89)) (:foreground "#c397d8"))))
 '(diredp-write-priv ((((class color) (min-colors 89)) (:foreground "#e7c547" :background nil))))
 '(magit-branch ((((class color) (min-colors 89)) (:foreground "DarkOliveGreen3"))))
 '(magit-diff-add ((((class color) (min-colors 89)) (:inherit diff-added))))
 '(magit-diff-del ((((class color) (min-colors 89)) (:inherit diff-removed))))
 '(magit-header ((((class color) (min-colors 89)) (:inherit nil :weight bold))))
 '(magit-item-highlight ((((class color) (min-colors 89)) (:inherit highlight :background nil))))
 '(magit-log-author ((((class color) (min-colors 89)) (:foreground "#70c0b1"))))
 '(magit-log-graph ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(magit-log-head-label-bisect-bad ((((class color) (min-colors 89)) (:foreground "#d54e53"))))
 '(magit-log-head-label-bisect-good ((((class color) (min-colors 89)) (:foreground "DarkOliveGreen3"))))
 '(magit-log-head-label-default ((((class color) (min-colors 89)) (:foreground "#e7c547" :box nil :weight bold))))
 '(magit-log-head-label-local ((((class color) (min-colors 89)) (:foreground "#c397d8" :box nil :weight bold))))
 '(magit-log-head-label-remote ((((class color) (min-colors 89)) (:foreground "#c397d8" :box nil :weight bold))))
 '(magit-log-head-label-tags ((((class color) (min-colors 89)) (:foreground "#70c0b1" :box nil :weight bold))))
 '(magit-log-sha1 ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(magit-section-title ((((class color) (min-colors 89)) (:foreground "DeepSkyBlue1" :weight bold))))
 '(git-gutter:modified ((((class color) (min-colors 89)) (:foreground "#c397d8" :weight bold))))
 '(git-gutter:added ((((class color) (min-colors 89)) (:foreground "DarkOliveGreen3" :weight bold))))
 '(git-gutter:deleted ((((class color) (min-colors 89)) (:foreground "#d54e53" :weight bold))))
 '(git-gutter:unchanged ((((class color) (min-colors 89)) (:background "#e7c547"))))
 '(git-gutter-fr:modified ((((class color) (min-colors 89)) (:foreground "#c397d8" :weight bold))))
 '(git-gutter-fr:added ((((class color) (min-colors 89)) (:foreground "DarkOliveGreen3" :weight bold))))
 '(git-gutter-fr:deleted ((((class color) (min-colors 89)) (:foreground "#d54e53" :weight bold))))
 '(link ((((class color) (min-colors 89)) (:foreground nil :underline t))))
 '(widget-button ((((class color) (min-colors 89)) (:underline t))))
 '(widget-field ((((class color) (min-colors 89)) (:background "#121212" :box (:line-width 1 :color "#eaeaea")))))
 '(compilation-column-number ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(compilation-line-number ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(compilation-message-face ((((class color) (min-colors 89)) (:foreground "DeepSkyBlue1"))))
 '(compilation-mode-line-exit ((((class color) (min-colors 89)) (:foreground "DarkOliveGreen3"))))
 '(compilation-mode-line-fail ((((class color) (min-colors 89)) (:foreground "#d54e53"))))
 '(compilation-mode-line-run ((((class color) (min-colors 89)) (:foreground "DeepSkyBlue1"))))
 '(grep-context-face ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(grep-error-face ((((class color) (min-colors 89)) (:foreground "#d54e53" :weight bold :underline t))))
 '(grep-hit-face ((((class color) (min-colors 89)) (:foreground "DeepSkyBlue1"))))
 '(grep-match-face ((((class color) (min-colors 89)) (:foreground nil :background nil :inherit match))))
 '(regex-tool-matched-face ((((class color) (min-colors 89)) (:foreground nil :background nil :inherit match))))
 '(mm/master-face ((((class color) (min-colors 89)) (:inherit region :foreground nil :background nil))))
 '(mm/mirror-face ((((class color) (min-colors 89)) (:inherit region :foreground nil :background nil))))
 '(org-agenda-structure ((((class color) (min-colors 89)) (:foreground "#c397d8"))))
 '(org-agenda-date ((((class color) (min-colors 89)) (:foreground "DeepSkyBlue1" :underline nil))))
 '(org-agenda-done ((((class color) (min-colors 89)) (:foreground "DarkOliveGreen3"))))
 '(org-agenda-dimmed-todo-face ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(org-block ((((class color) (min-colors 89)) (:foreground "goldenrod"))))
 '(org-block-background ((((class color) (min-colors 89)) (:background "#262626"))))
 '(org-code ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(org-column ((((class color) (min-colors 89)) (:background "#121212"))))
 '(org-column-title ((((class color) (min-colors 89)) (:inherit org-column :weight bold :underline t))))
 '(org-date ((((class color) (min-colors 89)) (:foreground "DeepSkyBlue1" :underline t))))
 '(org-document-info ((((class color) (min-colors 89)) (:foreground "#70c0b1"))))
 '(org-document-info-keyword ((((class color) (min-colors 89)) (:foreground "DarkOliveGreen3"))))
 '(org-document-title ((((class color) (min-colors 89)) (:weight bold :foreground "goldenrod" :height 1.44))))
 '(org-done ((((class color) (min-colors 89)) (:foreground "DarkOliveGreen3"))))
 '(org-ellipsis ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(org-footnote ((((class color) (min-colors 89)) (:foreground "#70c0b1"))))
 '(org-formula ((((class color) (min-colors 89)) (:foreground "#d54e53"))))
 '(org-hide ((((class color) (min-colors 89)) (:foreground "#1c1c1c" :background "#1c1c1c"))))
 '(org-link ((((class color) (min-colors 89)) (:foreground "DeepSkyBlue1" :underline t))))
 '(org-scheduled ((((class color) (min-colors 89)) (:foreground "DarkOliveGreen3"))))
 '(org-scheduled-previously ((((class color) (min-colors 89)) (:foreground "goldenrod"))))
 '(org-scheduled-today ((((class color) (min-colors 89)) (:foreground "DarkOliveGreen3"))))
 '(org-special-keyword ((((class color) (min-colors 89)) (:foreground "goldenrod"))))
 '(org-table ((((class color) (min-colors 89)) (:foreground "#c397d8"))))
 '(org-todo ((((class color) (min-colors 89)) (:foreground "#d54e53"))))
 '(org-upcoming-deadline ((((class color) (min-colors 89)) (:foreground "goldenrod"))))
 '(org-warning ((((class color) (min-colors 89)) (:weight bold :foreground "#d54e53"))))
 '(markdown-url-face ((((class color) (min-colors 89)) (:inherit link))))
 '(markdown-link-face ((((class color) (min-colors 89)) (:foreground "DeepSkyBlue1" :underline t))))
 '(hl-sexp-face ((((class color) (min-colors 89)) (:background "#121212"))))
 '(highlight-symbol-face ((((class color) (min-colors 89)) (:background "#103050"))))
 '(highlight-80+ ((((class color) (min-colors 89)) (:background "#121212"))))
 '(py-builtins-face ((((class color) (min-colors 89)) (:foreground "goldenrod" :weight normal))))
 '(js2-warning ((((class color) (min-colors 89)) (:underline "goldenrod"))))
 '(js2-error ((((class color) (min-colors 89)) (:foreground nil :underline "#d54e53"))))
 '(js2-external-variable ((((class color) (min-colors 89)) (:foreground "#c397d8"))))
 '(js2-function-param ((((class color) (min-colors 89)) (:foreground "DeepSkyBlue1"))))
 '(js2-instance-member ((((class color) (min-colors 89)) (:foreground "DeepSkyBlue1"))))
 '(js2-private-function-call ((((class color) (min-colors 89)) (:foreground "#d54e53"))))
 '(js3-warning-face ((((class color) (min-colors 89)) (:underline "goldenrod"))))
 '(js3-error-face ((((class color) (min-colors 89)) (:foreground nil :underline "#d54e53"))))
 '(js3-external-variable-face ((((class color) (min-colors 89)) (:foreground "#c397d8"))))
 '(js3-function-param-face ((((class color) (min-colors 89)) (:foreground "DeepSkyBlue1"))))
 '(js3-jsdoc-tag-face ((((class color) (min-colors 89)) (:foreground "goldenrod"))))
 '(js3-jsdoc-type-face ((((class color) (min-colors 89)) (:foreground "#70c0b1"))))
 '(js3-jsdoc-value-face ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(js3-jsdoc-html-tag-name-face ((((class color) (min-colors 89)) (:foreground "DeepSkyBlue1"))))
 '(js3-jsdoc-html-tag-delimiter-face ((((class color) (min-colors 89)) (:foreground "DarkOliveGreen3"))))
 '(js3-instance-member-face ((((class color) (min-colors 89)) (:foreground "DeepSkyBlue1"))))
 '(js3-private-function-call-face ((((class color) (min-colors 89)) (:foreground "#d54e53"))))
 '(coffee-mode-class-name ((((class color) (min-colors 89)) (:foreground "goldenrod" :weight bold))))
 '(coffee-mode-function-param ((((class color) (min-colors 89)) (:foreground "#c397d8"))))
 '(nxml-name-face ((((class color) (min-colors 89)) (:foreground unspecified :inherit font-lock-constant-face))))
 '(nxml-attribute-local-name-face ((((class color) (min-colors 89)) (:foreground unspecified :inherit font-lock-variable-name-face))))
 '(nxml-ref-face ((((class color) (min-colors 89)) (:foreground unspecified :inherit font-lock-preprocessor-face))))
 '(nxml-delimiter-face ((((class color) (min-colors 89)) (:foreground unspecified :inherit font-lock-keyword-face))))
 '(nxml-delimited-data-face ((((class color) (min-colors 89)) (:foreground unspecified :inherit font-lock-string-face))))
 '(rng-error-face ((((class color) (min-colors 89)) (:underline "#d54e53"))))
 '(erb-delim-face ((((class color) (min-colors 89)) (:background "#121212"))))
 '(erb-exec-face ((((class color) (min-colors 89)) (:background "#121212" :weight bold))))
 '(erb-exec-delim-face ((((class color) (min-colors 89)) (:background "#121212"))))
 '(erb-out-face ((((class color) (min-colors 89)) (:background "#121212" :weight bold))))
 '(erb-out-delim-face ((((class color) (min-colors 89)) (:background "#121212"))))
 '(erb-comment-face ((((class color) (min-colors 89)) (:background "#121212" :weight bold :slant italic))))
 '(erb-comment-delim-face ((((class color) (min-colors 89)) (:background "#121212"))))
 '(message-header-other ((((class color) (min-colors 89)) (:foreground nil :background nil :weight normal))))
 '(message-header-subject ((((class color) (min-colors 89)) (:inherit message-header-other :weight bold :foreground "#e7c547"))))
 '(message-header-to ((((class color) (min-colors 89)) (:inherit message-header-other :weight bold :foreground "goldenrod"))))
 '(message-header-cc ((((class color) (min-colors 89)) (:inherit message-header-to :foreground nil))))
 '(message-header-name ((((class color) (min-colors 89)) (:foreground "DeepSkyBlue1" :background nil))))
 '(message-header-newsgroups ((((class color) (min-colors 89)) (:foreground "#70c0b1" :background nil :slant normal))))
 '(message-separator ((((class color) (min-colors 89)) (:foreground "#c397d8"))))
 '(jabber-chat-prompt-local ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(jabber-chat-prompt-foreign ((((class color) (min-colors 89)) (:foreground "goldenrod"))))
 '(jabber-chat-prompt-system ((((class color) (min-colors 89)) (:foreground "#e7c547" :weight bold))))
 '(jabber-chat-text-local ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(jabber-chat-text-foreign ((((class color) (min-colors 89)) (:foreground "goldenrod"))))
 '(jabber-chat-text-error ((((class color) (min-colors 89)) (:foreground "#d54e53"))))
 '(jabber-roster-user-online ((((class color) (min-colors 89)) (:foreground "DarkOliveGreen3"))))
 '(jabber-roster-user-xa ((((class color) (min-colors 89)) :foreground "#969896")))
 '(jabber-roster-user-dnd ((((class color) (min-colors 89)) :foreground "#e7c547")))
 '(jabber-roster-user-away ((((class color) (min-colors 89)) (:foreground "goldenrod"))))
 '(jabber-roster-user-chatty ((((class color) (min-colors 89)) (:foreground "#c397d8"))))
 '(jabber-roster-user-error ((((class color) (min-colors 89)) (:foreground "#d54e53"))))
 '(jabber-roster-user-offline ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(jabber-rare-time-face ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(jabber-activity-face ((((class color) (min-colors 89)) (:foreground "#c397d8"))))
 '(jabber-activity-personal-face ((((class color) (min-colors 89)) (:foreground "#70c0b1"))))
 '(powerline-active1 ((t (:foreground "#eaeaea" :background "#103050"))))
 '(powerline-active2 ((t (:foreground "#eaeaea" :background "#121212"))))
 '(outline-1 ((((class color) (min-colors 89)) (:inherit nil :foreground "SkyBlue1"))))
 '(outline-2 ((((class color) (min-colors 89)) (:inherit nil :foreground "#e7c547"))))
 '(outline-3 ((((class color) (min-colors 89)) (:inherit nil :foreground "#c397d8"))))
 '(outline-4 ((((class color) (min-colors 89)) (:inherit nil :foreground "#70c0b1"))))
 '(outline-5 ((((class color) (min-colors 89)) (:inherit nil :foreground "goldenrod"))))
 '(outline-6 ((((class color) (min-colors 89)) (:inherit nil :foreground "CadetBlue1"))))
 '(outline-7 ((((class color) (min-colors 89)) (:inherit nil :foreground "aquamarine1"))))
 '(outline-8 ((((class color) (min-colors 89)) (:inherit nil :foreground "turquoise2"))))
 '(outline-9 ((((class color) (min-colors 89)) (:inherit nil :foreground "LightSteelBlue1"))))
 '(ledger-font-comment-face ((((class color) (min-colors 89)) (:inherit font-lock-comment-face))))
 '(ledger-font-occur-narrowed-face ((((class color) (min-colors 89)) (:inherit font-lock-comment-face :invisible t))))
 '(ledger-font-occur-xact-face ((((class color) (min-colors 89)) (:inherit highlight))))
 '(ledger-font-payee-cleared-face ((((class color) (min-colors 89)) (:foreground "DarkOliveGreen3"))))
 '(ledger-font-payee-uncleared-face ((((class color) (min-colors 89)) (:foreground "#70c0b1"))))
 '(ledger-font-posting-account-cleared-face ((((class color) (min-colors 89)) (:foreground "DeepSkyBlue1"))))
 '(ledger-font-posting-account-face ((((class color) (min-colors 89)) (:foreground "#c397d8"))))
 '(ledger-font-posting-account-pending-face ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(ledger-font-xact-highlight-face ((((class color) (min-colors 89)) (:inherit highlight))))
 '(ledger-occur-narrowed-face ((((class color) (min-colors 89)) (:inherit font-lock-comment-face :invisible t))))
 '(ledger-occur-xact-face ((((class color) (min-colors 89)) (:inherit highlight))))
 '(mu4e-header-highlight-face ((((class color) (min-colors 89)) (:underline nil :inherit region))))
 '(mu4e-header-marks-face ((((class color) (min-colors 89)) (:underline nil :foreground "#e7c547"))))
 '(mu4e-flagged-face ((((class color) (min-colors 89)) (:foreground "goldenrod" :inherit nil))))
 '(mu4e-replied-face ((((class color) (min-colors 89)) (:foreground "DeepSkyBlue1" :inherit nil))))
 '(mu4e-unread-face ((((class color) (min-colors 89)) (:foreground "#e7c547" :inherit nil))))
 '(mu4e-cited-1-face ((((class color) (min-colors 89)) (:inherit outline-1 :slant normal))))
 '(mu4e-cited-2-face ((((class color) (min-colors 89)) (:inherit outline-2 :slant normal))))
 '(mu4e-cited-3-face ((((class color) (min-colors 89)) (:inherit outline-3 :slant normal))))
 '(mu4e-cited-4-face ((((class color) (min-colors 89)) (:inherit outline-4 :slant normal))))
 '(mu4e-cited-5-face ((((class color) (min-colors 89)) (:inherit outline-5 :slant normal))))
 '(mu4e-cited-6-face ((((class color) (min-colors 89)) (:inherit outline-6 :slant normal))))
 '(mu4e-cited-7-face ((((class color) (min-colors 89)) (:inherit outline-7 :slant normal))))
 '(mu4e-ok-face ((((class color) (min-colors 89)) (:foreground "DarkOliveGreen3"))))
 '(mu4e-view-contact-face ((((class color) (min-colors 89)) (:inherit nil :foreground "#e7c547"))))
 '(mu4e-view-link-face ((((class color) (min-colors 89)) (:inherit link :foreground "DeepSkyBlue1"))))
 '(mu4e-view-url-number-face ((((class color) (min-colors 89)) (:inherit nil :foreground "#70c0b1"))))
 '(mu4e-view-attach-number-face ((((class color) (min-colors 89)) (:inherit nil :foreground "goldenrod"))))
 '(mu4e-highlight-face ((((class color) (min-colors 89)) (:inherit highlight))))
 '(mu4e-title-face ((((class color) (min-colors 89)) (:inherit nil :foreground "DarkOliveGreen3"))))
 '(gnus-cite-1 ((((class color) (min-colors 89)) (:inherit outline-1 :foreground nil))))
 '(gnus-cite-2 ((((class color) (min-colors 89)) (:inherit outline-2 :foreground nil))))
 '(gnus-cite-3 ((((class color) (min-colors 89)) (:inherit outline-3 :foreground nil))))
 '(gnus-cite-4 ((((class color) (min-colors 89)) (:inherit outline-4 :foreground nil))))
 '(gnus-cite-5 ((((class color) (min-colors 89)) (:inherit outline-5 :foreground nil))))
 '(gnus-cite-6 ((((class color) (min-colors 89)) (:inherit outline-6 :foreground nil))))
 '(gnus-cite-7 ((((class color) (min-colors 89)) (:inherit outline-7 :foreground nil))))
 '(gnus-cite-8 ((((class color) (min-colors 89)) (:inherit outline-8 :foreground nil))))
 '(gnus-header-content ((((class color) (min-colors 89)) (:inherit message-header-other))))
 '(gnus-header-subject ((((class color) (min-colors 89)) (:inherit message-header-subject))))
 '(gnus-header-from ((((class color) (min-colors 89)) (:inherit message-header-other-face :weight bold :foreground "goldenrod"))))
 '(gnus-header-name ((((class color) (min-colors 89)) (:inherit message-header-name))))
 '(gnus-button ((((class color) (min-colors 89)) (:inherit link :foreground nil))))
 '(gnus-signature ((((class color) (min-colors 89)) (:inherit font-lock-comment-face))))
 '(gnus-summary-normal-unread ((((class color) (min-colors 89)) (:foreground "DeepSkyBlue1" :weight normal))))
 '(gnus-summary-normal-read ((((class color) (min-colors 89)) (:foreground "#eaeaea" :weight normal))))
 '(gnus-summary-normal-ancient ((((class color) (min-colors 89)) (:foreground "#70c0b1" :weight normal))))
 '(gnus-summary-normal-ticked ((((class color) (min-colors 89)) (:foreground "goldenrod" :weight normal))))
 '(gnus-summary-low-unread ((((class color) (min-colors 89)) (:foreground "#969896" :weight normal))))
 '(gnus-summary-low-read ((((class color) (min-colors 89)) (:foreground "#969896" :weight normal))))
 '(gnus-summary-low-ancient ((((class color) (min-colors 89)) (:foreground "#969896" :weight normal))))
 '(gnus-summary-high-unread ((((class color) (min-colors 89)) (:foreground "#e7c547" :weight normal))))
 '(gnus-summary-high-read ((((class color) (min-colors 89)) (:foreground "DarkOliveGreen3" :weight normal))))
 '(gnus-summary-high-ancient ((((class color) (min-colors 89)) (:foreground "DarkOliveGreen3" :weight normal))))
 '(gnus-summary-high-ticked ((((class color) (min-colors 89)) (:foreground "goldenrod" :weight normal))))
 '(gnus-summary-cancelled ((((class color) (min-colors 89)) (:foreground "#d54e53" :background nil :weight normal))))
 '(gnus-group-mail-low ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(gnus-group-mail-low-empty ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(gnus-group-mail-1 ((((class color) (min-colors 89)) (:foreground nil :weight normal :inherit outline-1))))
 '(gnus-group-mail-2 ((((class color) (min-colors 89)) (:foreground nil :weight normal :inherit outline-2))))
 '(gnus-group-mail-3 ((((class color) (min-colors 89)) (:foreground nil :weight normal :inherit outline-3))))
 '(gnus-group-mail-4 ((((class color) (min-colors 89)) (:foreground nil :weight normal :inherit outline-4))))
 '(gnus-group-mail-5 ((((class color) (min-colors 89)) (:foreground nil :weight normal :inherit outline-5))))
 '(gnus-group-mail-6 ((((class color) (min-colors 89)) (:foreground nil :weight normal :inherit outline-6))))
 '(gnus-group-mail-1-empty ((((class color) (min-colors 89)) (:inherit gnus-group-mail-1 :foreground "#969896"))))
 '(gnus-group-mail-2-empty ((((class color) (min-colors 89)) (:inherit gnus-group-mail-2 :foreground "#969896"))))
 '(gnus-group-mail-3-empty ((((class color) (min-colors 89)) (:inherit gnus-group-mail-3 :foreground "#969896"))))
 '(gnus-group-mail-4-empty ((((class color) (min-colors 89)) (:inherit gnus-group-mail-4 :foreground "#969896"))))
 '(gnus-group-mail-5-empty ((((class color) (min-colors 89)) (:inherit gnus-group-mail-5 :foreground "#969896"))))
 '(gnus-group-mail-6-empty ((((class color) (min-colors 89)) (:inherit gnus-group-mail-6 :foreground "#969896"))))
 '(gnus-group-news-1 ((((class color) (min-colors 89)) (:foreground nil :weight normal :inherit outline-5))))
 '(gnus-group-news-2 ((((class color) (min-colors 89)) (:foreground nil :weight normal :inherit outline-6))))
 '(gnus-group-news-3 ((((class color) (min-colors 89)) (:foreground nil :weight normal :inherit outline-7))))
 '(gnus-group-news-4 ((((class color) (min-colors 89)) (:foreground nil :weight normal :inherit outline-8))))
 '(gnus-group-news-5 ((((class color) (min-colors 89)) (:foreground nil :weight normal :inherit outline-1))))
 '(gnus-group-news-6 ((((class color) (min-colors 89)) (:foreground nil :weight normal :inherit outline-2))))
 '(gnus-group-news-1-empty ((((class color) (min-colors 89)) (:inherit gnus-group-news-1 :foreground "#969896"))))
 '(gnus-group-news-2-empty ((((class color) (min-colors 89)) (:inherit gnus-group-news-2 :foreground "#969896"))))
 '(gnus-group-news-3-empty ((((class color) (min-colors 89)) (:inherit gnus-group-news-3 :foreground "#969896"))))
 '(gnus-group-news-4-empty ((((class color) (min-colors 89)) (:inherit gnus-group-news-4 :foreground "#969896"))))
 '(gnus-group-news-5-empty ((((class color) (min-colors 89)) (:inherit gnus-group-news-5 :foreground "#969896"))))
 '(gnus-group-news-6-empty ((((class color) (min-colors 89)) (:inherit gnus-group-news-6 :foreground "#969896"))))
 '(emms-playlist-selected-face ((((class color) (min-colors 89)) (:foreground "goldenrod"))))
 '(emms-playlist-track-face ((((class color) (min-colors 89)) (:foreground "DeepSkyBlue1"))))
 '(emms-browser-track-face ((((class color) (min-colors 89)) (:foreground "DeepSkyBlue1"))))
 '(emms-browser-artist-face ((((class color) (min-colors 89)) (:foreground "#d54e53" :height 1.3))))
 '(emms-browser-composer-face ((((class color) (min-colors 89)) (:inherit emms-browser-artist-face))))
 '(emms-browser-performer-face ((((class color) (min-colors 89)) (:inherit emms-browser-artist-face))))
 '(emms-browser-album-face ((((class color) (min-colors 89)) (:foreground "DarkOliveGreen3" :height 1.2))))
 '(stripe-highlight ((((class color) (min-colors 89)) (:background "#121212"))))
 '(stripe-hl-line ((((class color) (min-colors 89)) (:background "#103050" :foreground "#eaeaea"))))
 '(erc-direct-msg-face ((((class color) (min-colors 89)) (:foreground "goldenrod"))))
 '(erc-error-face ((((class color) (min-colors 89)) (:foreground "#d54e53"))))
 '(erc-header-face ((((class color) (min-colors 89)) (:foreground "#eaeaea" :background "#103050"))))
 '(erc-input-face ((((class color) (min-colors 89)) (:foreground "DarkOliveGreen3"))))
 '(erc-current-nick-face ((((class color) (min-colors 89)) (:foreground "DarkOliveGreen3"))))
 '(erc-my-nick-face ((((class color) (min-colors 89)) (:foreground "DarkOliveGreen3"))))
 '(erc-nick-default-face ((((class color) (min-colors 89)) (:weight normal :foreground "#c397d8"))))
 '(erc-nick-msg-face ((((class color) (min-colors 89)) (:weight normal :foreground "#e7c547"))))
 '(erc-notice-face ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(erc-pal-face ((((class color) (min-colors 89)) (:foreground "goldenrod"))))
 '(erc-prompt-face ((((class color) (min-colors 89)) (:foreground "DeepSkyBlue1"))))
 '(erc-timestamp-face ((((class color) (min-colors 89)) (:foreground "#70c0b1"))))
 '(erc-keyword-face ((((class color) (min-colors 89)) (:foreground "DarkOliveGreen3"))))
 '(twittering-username-face ((((class color) (min-colors 89)) (:inherit erc-pal-face))))
 '(twittering-uri-face ((((class color) (min-colors 89)) (:foreground "DeepSkyBlue1" :inherit link))))
 '(twittering-timeline-header-face ((((class color) (min-colors 89)) (:foreground "DarkOliveGreen3" :weight bold))))
 '(twittering-timeline-footer-face ((((class color) (min-colors 89)) (:inherit twittering-timeline-header-face))))
 '(custom-variable-tag ((((class color) (min-colors 89)) (:foreground "DeepSkyBlue1"))))
 '(custom-group-tag ((((class color) (min-colors 89)) (:foreground "DeepSkyBlue1"))))
 '(custom-state ((((class color) (min-colors 89)) (:foreground "DarkOliveGreen3"))))
 '(term ((((class color) (min-colors 89)) (:foreground nil :background nil :inherit default))))
 '(term-color-black ((((class color) (min-colors 89)) (:foreground "#eaeaea" :background "#eaeaea"))))
 '(term-color-red ((((class color) (min-colors 89)) (:foreground "#d54e53" :background "#d54e53"))))
 '(term-color-green ((((class color) (min-colors 89)) (:foreground "DarkOliveGreen3" :background "DarkOliveGreen3"))))
 '(term-color-yellow ((((class color) (min-colors 89)) (:foreground "#e7c547" :background "#e7c547"))))
 '(term-color-blue ((((class color) (min-colors 89)) (:foreground "DeepSkyBlue1" :background "DeepSkyBlue1"))))
 '(term-color-magenta ((((class color) (min-colors 89)) (:foreground "#c397d8" :background "#c397d8"))))
 '(term-color-cyan ((((class color) (min-colors 89)) (:foreground "#70c0b1" :background "#70c0b1"))))
 '(term-color-white ((((class color) (min-colors 89)) (:foreground "#1c1c1c" :background "#1c1c1c"))))
 '(default ((((class color) (min-colors 89)) (:foreground "#eaeaea" :background "undefined-bg")))))

(provide-theme 'afternoon)
