(deftheme monokai
  "Created 2014-07-01.")

(custom-theme-set-variables
 'monokai
 '(ansi-color-names-vector ["#1B1E1C" "#FF1493" "#87D700" "#CDC673" "#5FD7FF" "#D700D7" "#5FFFFF" "#F5F5F5"])
 '(compilation-message-face (quote default)))

(custom-theme-set-faces
 'monokai
 '(button ((t (:underline t))))
 '(shadow ((((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(match ((((class color) (min-colors 89)) (:background "#303030" :foreground "#FFFAFA" :weight bold))))
 '(cursor ((((class color) (min-colors 89)) (:foreground "#1B1E1C" :background "#F5F5F5" :inverse-video t))))
 '(mouse ((((class color) (min-colors 89)) (:foreground "#1B1E1C" :background "#F5F5F5" :inverse-video t))))
 '(escape-glyph-face ((((class color) (min-colors 89)) (:foreground "#FF1493"))))
 '(fringe ((((class color) (min-colors 89)) (:foreground "#F5F5F5" :background "#1B1E1C"))))
 '(highlight ((((class color) (min-colors 89)) (:background "#303030"))))
 '(link ((((class color) (min-colors 89)) (:foreground "#5FD7FF" :underline t :weight bold))))
 '(link-visited ((((class color) (min-colors 89)) (:foreground "#5FD7FF" :underline t :weight normal))))
 '(success ((((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(warning ((((class color) (min-colors 89)) (:foreground "#CDC673"))))
 '(error ((((class color) (min-colors 89)) (:foreground "#FF8C00"))))
 '(lazy-highlight ((((class color) (min-colors 89)) (:foreground "#1B1E1C" :background "#CDC673" :weight normal))))
 '(escape-glyph ((((class color) (min-colors 89)) (:foreground "#AF87FF"))))
 '(compilation-column-face ((((class color) (min-colors 89)) (:foreground "#5FFFFF" :underline nil))))
 '(compilation-column-number ((((class color) (min-colors 89)) (:inherit font-lock-doc-face :foreground "#5FFFFF" :underline nil))))
 '(compilation-enter-directory-face ((((class color) (min-colors 89)) (:foreground "#87D700" :underline nil))))
 '(compilation-error ((((class color) (min-colors 89)) (:inherit error :underline nil))))
 '(compilation-error-face ((((class color) (min-colors 89)) (:foreground "#FF1493" :underline nil))))
 '(compilation-face ((((class color) (min-colors 89)) (:foreground "#F5F5F5" :underline nil))))
 '(compilation-info ((((class color) (min-colors 89)) (:foreground "#8B8878" :underline nil :bold nil))))
 '(compilation-info-face ((((class color) (min-colors 89)) (:foreground "#5FD7FF" :underline nil))))
 '(compilation-leave-directory-face ((((class color) (min-colors 89)) (:foreground "#87D700" :underline nil))))
 '(compilation-line-face ((((class color) (min-colors 89)) (:foreground "#87D700" :underline nil))))
 '(compilation-line-number ((((class color) (min-colors 89)) (:foreground "#87D700" :underline nil))))
 '(compilation-warning ((((class color) (min-colors 89)) (:inherit warning :underline nil))))
 '(compilation-warning-face ((((class color) (min-colors 89)) (:foreground "#CDC673" :weight normal :underline nil))))
 '(compilation-mode-line-exit ((((class color) (min-colors 89)) (:inherit compilation-info :foreground "#87D700" :weight bold))))
 '(compilation-mode-line-fail ((((class color) (min-colors 89)) (:inherit compilation-error :foreground "#FF1493" :weight bold))))
 '(compilation-mode-line-run ((((class color) (min-colors 89)) (:foreground "#FF8C00" :weight bold))))
 '(cua-global-mark ((((class color) (min-colors 89)) (:background "#CDC673" :foreground "#1B1E1C"))))
 '(cua-rectangle ((((class color) (min-colors 89)) (:inherit region :background "#D700D7" :foreground "#1B1E1C"))))
 '(cua-rectangle-noselect ((((class color) (min-colors 89)) (:inherit region :background "#303030" :foreground "#8B8878"))))
 '(diary ((((class color) (min-colors 89)) (:foreground "#CDC673"))))
 '(dired-directory ((((class color) (min-colors 89)) (:foreground "#5FD7FF" :weight normal))))
 '(dired-flagged ((((class color) (min-colors 89)) (:foreground "#FF1493"))))
 '(dired-header ((((class color) (min-colors 89)) (:foreground "#1B1E1C" :background "#5FD7FF"))))
 '(dired-ignored ((((class color) (min-colors 89)) (:inherit shadow))))
 '(dired-mark ((((class color) (min-colors 89)) (:foreground "#CDC673" :weight bold))))
 '(dired-marked ((((class color) (min-colors 89)) (:foreground "#D700D7" :weight bold))))
 '(dired-perm-write ((((class color) (min-colors 89)) (:foreground "#F5F5F5" :underline t))))
 '(dired-symlink ((((class color) (min-colors 89)) (:foreground "#5FFFFF" :weight normal :slant italic))))
 '(dired-warning ((((class color) (min-colors 89)) (:foreground "#FF8C00" :underline t))))
 '(dropdown-list-face ((((class color) (min-colors 89)) (:background "#303030" :foreground "#5FFFFF"))))
 '(dropdown-list-selection-face ((((class color) (min-colors 89)) (:background "#AFEEEE" :foreground "#349B8D"))))
 '(ecb-default-highlight-face ((((class color) (min-colors 89)) (:background "#5FD7FF" :foreground "#1B1E1C"))))
 '(ecb-history-bucket-node-dir-soure-path-face ((((class color) (min-colors 89)) (:inherit ecb-history-bucket-node-face :foreground "#CDC673"))))
 '(ecb-source-in-directories-buffer-face ((((class color) (min-colors 89)) (:inherit ecb-directories-general-face :foreground "#F5F5F5"))))
 '(ecb-history-dead-buffer-face ((((class color) (min-colors 89)) (:inherit ecb-history-general-face :foreground "#8B8878"))))
 '(ecb-directory-not-accessible-face ((((class color) (min-colors 89)) (:inherit ecb-directories-general-face :foreground "#8B8878"))))
 '(ecb-bucket-node-face ((((class color) (min-colors 89)) (:inherit ecb-default-general-face :weight normal :foreground "#5FD7FF"))))
 '(ecb-tag-header-face ((((class color) (min-colors 89)) (:background "#303030"))))
 '(ecb-analyse-bucket-element-face ((((class color) (min-colors 89)) (:inherit ecb-analyse-general-face :foreground "#87D700"))))
 '(ecb-directories-general-face ((((class color) (min-colors 89)) (:inherit ecb-default-general-face :height 1.0))))
 '(ecb-method-non-semantic-face ((((class color) (min-colors 89)) (:inherit ecb-methods-general-face :foreground "#5FFFFF"))))
 '(ecb-mode-line-prefix-face ((((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(ecb-tree-guide-line-face ((((class color) (min-colors 89)) (:inherit ecb-default-general-face :foreground "#303030" :height 1.0))))
 '(ee-bookmarked ((((class color) (min-colors 89)) (:foreground "#FFFAFA"))))
 '(ee-category ((((class color) (min-colors 89)) (:foreground "#5FD7FF"))))
 '(ee-link ((((class color) (min-colors 89)) (:inherit link))))
 '(ee-link-visited ((((class color) (min-colors 89)) (:inherit link-visited))))
 '(ee-marked ((((class color) (min-colors 89)) (:foreground "#D700D7" :weight bold))))
 '(ee-omitted ((((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(ee-shadow ((((class color) (min-colors 89)) (:inherit shadow))))
 '(grep-context-face ((((class color) (min-colors 89)) (:foreground "#F5F5F5"))))
 '(grep-error-face ((((class color) (min-colors 89)) (:foreground "#FF1493" :weight bold :underline t))))
 '(grep-hit-face ((((class color) (min-colors 89)) (:foreground "#5FD7FF"))))
 '(grep-match-face ((((class color) (min-colors 89)) (:foreground "#FF8C00" :weight bold))))
 '(isearch ((((class color) (min-colors 89)) (:foreground "#1B1E1C" :background "#D700D7" :weight normal))))
 '(isearch-fail ((((class color) (min-colors 89)) (:foreground "#FF1493" :background "#1B1E1C" :bold t))))
 '(Man-overstrike ((((class color) (min-colors 89)) (:foreground "#5FD7FF" :weight bold))))
 '(Man-reverse ((((class color) (min-colors 89)) (:foreground "#FF8C00"))))
 '(Man-underline ((((class color) (min-colors 89)) (:foreground "#87D700" :underline t))))
 '(menu ((((class color) (min-colors 89)) (:foreground "#F5F5F5" :background "#1B1E1C"))))
 '(minibuffer-prompt ((((class color) (min-colors 89)) (:foreground "#5FD7FF"))))
 '(mode-line ((((class color) (min-colors 89)) (:inverse-video unspecified :underline unspecified :foreground "#F5F5F5" :background "#212121" :box (:line-width 1 :color "#212121" :style unspecified)))))
 '(mode-line-buffer-id ((((class color) (min-colors 89)) (:foreground "#87D700" :weight bold))))
 '(mode-line-inactive ((((class color) (min-colors 89)) (:inverse-video unspecified :underline unspecified :foreground "#8B8878" :background "#1B1E1C" :box (:line-width 1 :color "#212121" :style unspecified)))))
 '(header-line ((((class color) (min-colors 89)) (:inverse-video unspecified :underline unspecified :foreground "#FFFAFA" :background "#303030" :box (:line-width 1 :color "#303030" :style unspecified)))))
 '(region ((((class color) (min-colors 89)) (:background "#303030" :inherit t))))
 '(secondary-selection ((((class color) (min-colors 89)) (:background "#303030" :inherit t))))
 '(trailing-whitespace ((((class color) (min-colors 89)) (:background "#FF1493"))))
 '(vertical-border ((((class color) (min-colors 89)) (:foreground "#303030"))))
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "#FF1493" :weight normal))))
 '(font-lock-comment-delimiter-face ((((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(font-lock-comment-face ((((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(font-lock-constant-face ((((class color) (min-colors 89)) (:foreground "#AF87FF"))))
 '(font-lock-doc-face ((((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(font-lock-function-name-face ((((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(font-lock-keyword-face ((((class color) (min-colors 89)) (:foreground "#FF1493" :weight normal))))
 '(font-lock-negation-char-face ((((class color) (min-colors 89)) (:foreground "#CDC673" :weight bold))))
 '(font-lock-preprocessor-face ((((class color) (min-colors 89)) (:foreground "#FF1493"))))
 '(font-lock-regexp-grouping-construct ((((class color) (min-colors 89)) (:foreground "#CDC673" :weight normal))))
 '(font-lock-regexp-grouping-backslash ((((class color) (min-colors 89)) (:foreground "#AF87FF" :weight normal))))
 '(font-lock-string-face ((((class color) (min-colors 89)) (:foreground "#CDC673"))))
 '(font-lock-type-face ((((class color) (min-colors 89)) (:foreground "#5FD7FF" :italic t))))
 '(font-lock-variable-name-face ((((class color) (min-colors 89)) (:foreground "#FF8C00"))))
 '(font-lock-warning-face ((((class color) (min-colors 89)) (:foreground "#FF8C00" :weight bold :italic t :underline t))))
 '(c-annotation-face ((((class color) (min-colors 89)) (:inherit font-lock-constant-face))))
 '(ace-jump-face-background ((((class color) (min-colors 89)) (:foreground "#8B8878" :background "#1B1E1C" :inverse-video nil))))
 '(ace-jump-face-foreground ((((class color) (min-colors 89)) (:foreground "#FF1493" :background "#1B1E1C" :inverse-video nil :weight bold))))
 '(font-latex-bold-face ((((class color) (min-colors 89)) (:inherit bold :foreground "#FFFAFA"))))
 '(font-latex-doctex-documentation-face ((((class color) (min-colors 89)) (:background unspecified))))
 '(font-latex-doctex-preprocessor-face ((((class color) (min-colors 89)) (:inherit (font-latex-doctex-documentation-face font-lock-builtin-face font-lock-preprocessor-face)))))
 '(font-latex-italic-face ((((class color) (min-colors 89)) (:inherit italic :foreground "#FFFAFA"))))
 '(font-latex-math-face ((((class color) (min-colors 89)) (:foreground "#AF87FF"))))
 '(font-latex-sectioning-0-face ((((class color) (min-colors 89)) (:inherit font-latex-sectioning-1-face :height 1.1))))
 '(font-latex-sectioning-1-face ((((class color) (min-colors 89)) (:inherit font-latex-sectioning-2-face :height 1.1))))
 '(font-latex-sectioning-2-face ((((class color) (min-colors 89)) (:inherit font-latex-sectioning-3-face :height 1.1))))
 '(font-latex-sectioning-3-face ((((class color) (min-colors 89)) (:inherit font-latex-sectioning-4-face :height 1.1))))
 '(font-latex-sectioning-4-face ((((class color) (min-colors 89)) (:inherit font-latex-sectioning-5-face :height 1.1))))
 '(font-latex-sectioning-5-face ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#CDC673" :weight bold))))
 '(font-latex-sedate-face ((((class color) (min-colors 89)) (:foreground "#FFFAFA"))))
 '(font-latex-slide-title-face ((((class color) (min-colors 89)) (:inherit (variable-pitch font-lock-type-face) :weight bold :height 1.2))))
 '(font-latex-string-face ((((class color) (min-colors 89)) (:foreground "#5FFFFF"))))
 '(font-latex-subscript-face ((((class color) (min-colors 89)) (:height 0.8))))
 '(font-latex-superscript-face ((((class color) (min-colors 89)) (:height 0.8))))
 '(font-latex-verbatim-face ((((class color) (min-colors 89)) (:inherit fixed-pitch :foreground "#F5F5F5" :slant italic))))
 '(font-latex-warning-face ((((class color) (min-colors 89)) (:inherit bold :foreground "#FF8C00"))))
 '(ac-candidate-face ((((class color) (min-colors 89)) (:background "#303030" :foreground "#5FFFFF"))))
 '(ac-selection-face ((((class color) (min-colors 89)) (:background "#AFEEEE" :foreground "#349B8D"))))
 '(ac-candidate-mouse-face ((((class color) (min-colors 89)) (:background "#349B8D" :foreground "#AFEEEE"))))
 '(ac-completion-face ((((class color) (min-colors 89)) (:foreground "#FFFAFA" :underline t))))
 '(ac-gtags-candidate-face ((((class color) (min-colors 89)) (:background "#303030" :foreground "#5FD7FF"))))
 '(ac-gtags-selection-face ((((class color) (min-colors 89)) (:background "#8DE6F7" :foreground "#21889B"))))
 '(ac-yasnippet-candidate-face ((((class color) (min-colors 89)) (:background "#303030" :foreground "#CDC673"))))
 '(ac-yasnippet-selection-face ((((class color) (min-colors 89)) (:background "#FFF68F" :foreground "#968B26"))))
 '(ahs-definition-face ((((class color) (min-colors 89)) (:foreground "#D700D7" :background unspecified :slant normal))))
 '(ahs-edit-mode-face ((((class color) (min-colors 89)) (:foreground "#1B1E1C" :background "#D700D7"))))
 '(ahs-face ((((class color) (min-colors 89)) (:foreground "#D700D7" :background unspecified))))
 '(ahs-plugin-bod-face ((((class color) (min-colors 89)) (:foreground "#D700D7" :background unspecified))))
 '(ahs-plugin-defalt-face ((((class color) (min-colors 89)) (:foreground "#D700D7" :background unspecified))))
 '(ahs-plugin-whole-buffer-face ((((class color) (min-colors 89)) (:foreground "#D700D7" :background unspecified))))
 '(ahs-warning-face ((((class color) (min-colors 89)) (:foreground "#FF1493" :weight bold))))
 '(android-mode-debug-face ((((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(android-mode-error-face ((((class color) (min-colors 89)) (:foreground "#FF8C00" :weight bold))))
 '(android-mode-info-face ((((class color) (min-colors 89)) (:foreground "#F5F5F5"))))
 '(android-mode-verbose-face ((((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(android-mode-warning-face ((((class color) (min-colors 89)) (:foreground "#CDC673"))))
 '(anzu-mode-line ((((class color) (min-colors 89)) (:foreground "#D700D7" :weight bold))))
 '(bm-face ((((class color) (min-colors 89)) (:background "#FFF68F" :foreground "#1B1E1C"))))
 '(bm-fringe-face ((((class color) (min-colors 89)) (:background "#FFF68F" :foreground "#1B1E1C"))))
 '(bm-fringe-persistent-face ((((class color) (min-colors 89)) (:background "#B3EE3A" :foreground "#1B1E1C"))))
 '(bm-persistent-face ((((class color) (min-colors 89)) (:background "#B3EE3A" :foreground "#1B1E1C"))))
 '(cfw:face-day-title ((((class color) (min-colors 89)) (:background "#303030"))))
 '(cfw:face-annotation ((((class color) (min-colors 89)) (:inherit cfw:face-day-title :foreground "#CDC673"))))
 '(cfw:face-default-content ((((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(cfw:face-default-day ((((class color) (min-colors 89)) (:inherit cfw:face-day-title :weight bold))))
 '(cfw:face-disable ((((class color) (min-colors 89)) (:inherit cfw:face-day-title :foreground "#8B8878"))))
 '(cfw:face-grid ((((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(cfw:face-header ((((class color) (min-colors 89)) (:foreground "#21889B" :background "#8DE6F7" :weight bold))))
 '(cfw:face-holiday ((((class color) (min-colors 89)) (:background nil :foreground "#FF1493" :weight bold))))
 '(cfw:face-periods ((((class color) (min-colors 89)) (:foreground "#D700D7"))))
 '(cfw:face-select ((((class color) (min-colors 89)) (:background "#FE87F4" :foreground "#A41F99"))))
 '(cfw:face-saturday ((((class color) (min-colors 89)) (:foreground "#349B8D" :background "#AFEEEE"))))
 '(cfw:face-sunday ((((class color) (min-colors 89)) (:foreground "#5F0000" :background "#EE6AA7" :weight bold))))
 '(cfw:face-title ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#CDC673" :weight bold :height 1.3))))
 '(cfw:face-today ((((class color) (min-colors 89)) (:weight bold :background "#303030" :foreground nil))))
 '(cfw:face-today-title ((((class color) (min-colors 89)) (:background "#FFF68F" :foreground "#968B26" :weight bold))))
 '(cfw:face-toolbar ((((class color) (min-colors 89)) (:background "#303030" :foreground "#F5F5F5"))))
 '(cfw:face-toolbar-button-off ((((class color) (min-colors 89)) (:background "#FFF68F" :foreground "#968B26" :weight bold))))
 '(cfw:face-toolbar-button-on ((((class color) (min-colors 89)) (:background "#968B26" :foreground "#FFF68F" :weight bold))))
 '(clojure-test-failure-face ((t (:foreground "#FF8C00" :weight bold :underline t))))
 '(clojure-test-error-face ((t (:foreground "#FF1493" :weight bold :underline t))))
 '(clojure-test-success-face ((t (:foreground "#87D700" :weight bold :underline t))))
 '(company-tooltip ((((class color) (min-colors 89)) (:background "#303030" :foreground "#5FFFFF"))))
 '(company-tooltip-selection ((((class color) (min-colors 89)) (:background "#AFEEEE" :foreground "#349B8D"))))
 '(company-tooltip-mouse ((((class color) (min-colors 89)) (:background "#349B8D" :foreground "#AFEEEE"))))
 '(company-tooltip-common ((((class color) (min-colors 89)) (:foreground "#FFFAFA" :underline t))))
 '(company-tooltip-common-selection ((((class color) (min-colors 89)) (:foreground "#FFFAFA" :underline t))))
 '(company-preview ((((class color) (min-colors 89)) (:background "#303030" :foreground "#5FFFFF"))))
 '(company-preview-common ((((class color) (min-colors 89)) (:foreground "#FFFAFA" :underline t))))
 '(cscope-file-face ((((class color) (min-colors 89)) (:foreground "#87D700" :weight bold))))
 '(cscope-function-face ((((class color) (min-colors 89)) (:foreground "#5FD7FF"))))
 '(cscope-line-number-face ((((class color) (min-colors 89)) (:foreground "#CDC673"))))
 '(cscope-line-face ((((class color) (min-colors 89)) (:foreground "#F5F5F5"))))
 '(cscope-mouse-face ((((class color) (min-colors 89)) (:background "#5FD7FF" :foreground "#F5F5F5"))))
 '(ctbl:face-cell-select ((((class color) (min-colors 89)) (:background "#303030" :foreground "#FFFAFA" :underline "#FFFAFA" :weight bold))))
 '(ctbl:face-continue-bar ((((class color) (min-colors 89)) (:background "#303030" :foreground "#CDC673"))))
 '(ctbl:face-row-select ((((class color) (min-colors 89)) (:background "#303030" :foreground "#F5F5F5" :underline t))))
 '(coffee-mode-class-name ((((class color) (min-colors 89)) (:foreground "#CDC673" :weight bold))))
 '(coffee-mode-function-param ((((class color) (min-colors 89)) (:foreground "#AF87FF" :slant italic))))
 '(custom-face-tag ((((class color) (min-colors 89)) (:inherit variable-pitch :height 1.2 :foreground "#AF87FF" :weight bold))))
 '(custom-variable-tag ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#5FFFFF" :height 1.2))))
 '(custom-comment-tag ((((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(custom-group-tag ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#5FD7FF" :height 1.2))))
 '(custom-group-tag-1 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#FF1493" :height 1.2))))
 '(custom-state ((((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(diff-added ((((class color) (min-colors 89)) (:foreground "#87D700" :background "#1B1E1C"))))
 '(diff-changed ((((class color) (min-colors 89)) (:foreground "#5FD7FF" :background "#1B1E1C"))))
 '(diff-removed ((((class color) (min-colors 89)) (:foreground "#FF1493" :background "#1B1E1C"))))
 '(diff-header ((((class color) (min-colors 89)) (:background "#1B1E1C"))))
 '(diff-file-header ((((class color) (min-colors 89)) (:background "#1B1E1C" :foreground "#F5F5F5" :weight bold))))
 '(diff-refine-added ((((class color) (min-colors 89)) :foreground "#1B1E1C" :background "#87D700")))
 '(diff-refine-change ((((class color) (min-colors 89)) :foreground "#1B1E1C" :background "#5FD7FF")))
 '(diff-refine-removed ((((class color) (min-colors 89)) (:foreground "#1B1E1C" :background "#FF1493"))))
 '(ediff-fine-diff-A ((((class color) (min-colors 89)) (:background "#FFA54F"))))
 '(ediff-fine-diff-B ((((class color) (min-colors 89)) (:background "#B3EE3A"))))
 '(ediff-fine-diff-C ((((class color) (min-colors 89)) (:background "#FFF68F"))))
 '(ediff-current-diff-C ((((class color) (min-colors 89)) (:background "#8DE6F7"))))
 '(ediff-even-diff-A ((((class color) (min-colors 89)) (:background "#8B8878" :foreground "#141414"))))
 '(ediff-odd-diff-A ((((class color) (min-colors 89)) (:background "#8B8878" :foreground "#171A0B"))))
 '(ediff-even-diff-B ((((class color) (min-colors 89)) (:background "#8B8878" :foreground "#171A0B"))))
 '(ediff-odd-diff-B ((((class color) (min-colors 89)) (:background "#8B8878" :foreground "#141414"))))
 '(ediff-even-diff-C ((((class color) (min-colors 89)) (:background "#8B8878" :foreground "#F5F5F5"))))
 '(ediff-odd-diff-C ((((class color) (min-colors 89)) (:background "#8B8878" :foreground "#1B1E1C"))))
 '(diff-hl-change ((((class color) (min-colors 89)) (:background "#8DE6F7" :foreground "#21889B"))))
 '(diff-hl-delete ((((class color) (min-colors 89)) (:background "#EE6AA7" :foreground "#5F0000"))))
 '(diff-hl-insert ((((class color) (min-colors 89)) (:background "#B3EE3A" :foreground "#6B8E23"))))
 '(diff-hl-unknown ((((class color) (min-colors 89)) (:background "#AFEEEE" :foreground "#349B8D"))))
 '(edts-face-error-line ((((supports :underline (:style line)) (class color) (min-colors 89)) (:underline (:style line :color "#EE6AA7") :inherit unspecified)) (((class color) (min-colors 89)) (:foreground "#5F0000" :background "#EE6AA7" :weight bold :underline t))))
 '(edts-face-warning-line ((((supports :underline (:style line)) (class color) (min-colors 89)) (:underline (:style line :color "#FFF68F") :inherit unspecified)) (((class color) (min-colors 89)) (:foreground "#968B26" :background "#FFF68F" :weight bold :underline t))))
 '(edts-face-error-fringe-bitmap ((((class color) (min-colors 89)) (:foreground "#EE6AA7" :background unspecified :weight bold))))
 '(edts-face-warning-fringe-bitmap ((((class color) (min-colors 89)) (:foreground "#FFF68F" :background unspecified :weight bold))))
 '(edts-face-error-mode-line ((((class color) (min-colors 89)) (:background "#EE6AA7" :foreground unspecified))))
 '(edts-face-warning-mode-line ((((class color) (min-colors 89)) (:background "#FFF68F" :foreground unspecified))))
 '(elfeed-search-date-face ((((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(elfeed-search-feed-face ((((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(elfeed-search-tag-face ((((class color) (min-colors 89)) (:foreground "#F5F5F5"))))
 '(elfeed-search-title-face ((((class color) (min-colors 89)) (:foreground "#5FFFFF"))))
 '(enh-ruby-string-delimiter-face ((((class color) (min-colors 89)) (:inherit font-lock-string-face))))
 '(enh-ruby-heredoc-delimiter-face ((((class color) (min-colors 89)) (:inherit font-lock-string-face))))
 '(enh-ruby-regexp-delimiter-face ((((class color) (min-colors 89)) (:inherit font-lock-string-face))))
 '(enh-ruby-op-face ((((class color) (min-colors 89)) (:inherit font-lock-keyword-face))))
 '(erm-syn-errline ((((supports :underline (:style wave)) (class color) (min-colors 89)) (:underline (:style wave :color "#FF1493") :inherit unspecified)) (((class color) (min-colors 89)) (:foreground "#5F0000" :background "#EE6AA7" :weight bold :underline t))))
 '(erm-syn-warnline ((((supports :underline (:style wave)) (class color) (min-colors 89)) (:underline (:style wave :color "#FF8C00") :inherit unspecified)) (((class color) (min-colors 89)) (:foreground "#A0522D" :background "#FFA54F" :weight bold :underline t))))
 '(epc:face-title ((((class color) (min-colors 89)) (:foreground "#5FD7FF" :background "#1B1E1C" :weight normal :underline nil))))
 '(erc-action-face ((((class color) (min-colors 89)) (:inherit erc-default-face))))
 '(erc-bold-face ((((class color) (min-colors 89)) (:weight bold))))
 '(erc-current-nick-face ((((class color) (min-colors 89)) (:foreground "#5FD7FF" :weight bold))))
 '(erc-dangerous-host-face ((((class color) (min-colors 89)) (:inherit font-lock-warning-face))))
 '(erc-default-face ((((class color) (min-colors 89)) (:foreground "#F5F5F5"))))
 '(erc-highlight-face ((((class color) (min-colors 89)) (:inherit erc-default-face :background "#303030"))))
 '(erc-direct-msg-face ((((class color) (min-colors 89)) (:inherit erc-default-face))))
 '(erc-error-face ((((class color) (min-colors 89)) (:inherit font-lock-warning-face))))
 '(erc-fool-face ((((class color) (min-colors 89)) (:inherit erc-default-face))))
 '(erc-input-face ((((class color) (min-colors 89)) (:foreground "#CDC673"))))
 '(erc-keyword-face ((((class color) (min-colors 89)) (:foreground "#5FD7FF" :weight bold))))
 '(erc-nick-default-face ((((class color) (min-colors 89)) (:foreground "#CDC673" :weight bold))))
 '(erc-my-nick-face ((((class color) (min-colors 89)) (:foreground "#FF1493" :weight bold))))
 '(erc-nick-msg-face ((((class color) (min-colors 89)) (:inherit erc-default-face))))
 '(erc-notice-face ((((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(erc-pal-face ((((class color) (min-colors 89)) (:foreground "#FF8C00" :weight bold))))
 '(erc-prompt-face ((((class color) (min-colors 89)) (:foreground "#FF8C00" :background "#1B1E1C" :weight bold))))
 '(erc-timestamp-face ((((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(erc-underline-face ((t (:underline t))))
 '(eshell-prompt ((((class color) (min-colors 89)) (:foreground "#CDC673" :weight bold))))
 '(eshell-ls-archive ((((class color) (min-colors 89)) (:foreground "#FF1493" :weight bold))))
 '(eshell-ls-backup ((((class color) (min-colors 89)) (:inherit font-lock-comment-face))))
 '(eshell-ls-clutter ((((class color) (min-colors 89)) (:inherit font-lock-comment-face))))
 '(eshell-ls-directory ((((class color) (min-colors 89)) (:foreground "#5FD7FF" :weight bold))))
 '(eshell-ls-executable ((((class color) (min-colors 89)) (:foreground "#FF1493" :weight bold))))
 '(eshell-ls-unreadable ((((class color) (min-colors 89)) (:foreground "#F5F5F5"))))
 '(eshell-ls-missing ((((class color) (min-colors 89)) (:inherit font-lock-warning-face))))
 '(eshell-ls-product ((((class color) (min-colors 89)) (:inherit font-lock-doc-face))))
 '(eshell-ls-special ((((class color) (min-colors 89)) (:foreground "#CDC673" :weight bold))))
 '(eshell-ls-symlink ((((class color) (min-colors 89)) (:foreground "#5FFFFF" :weight bold))))
 '(fic-author-face ((((class color) (min-colors 89)) (:background "#1B1E1C" :foreground "#FF8C00" :underline t :slant italic))))
 '(fic-face ((((class color) (min-colors 89)) (:background "#1B1E1C" :foreground "#FF8C00" :weight normal :slant italic))))
 '(font-lock-fic-face ((((class color) (min-colors 89)) (:background "#1B1E1C" :foreground "#FF8C00" :weight normal :slant italic))))
 '(flx-highlight-face ((((class color) (min-colors 89)) (:foreground "#5FD7FF" :weight normal :underline nil))))
 '(flymake-errline ((((supports :underline (:style wave)) (class color) (min-colors 89)) (:underline (:style wave :color "#FF1493") :inherit unspecified :foreground unspecified :background unspecified)) (((class color) (min-colors 89)) (:foreground "#5F0000" :background "#EE6AA7" :weight bold :underline t))))
 '(flymake-infoline ((((supports :underline (:style wave)) (class color) (min-colors 89)) (:underline (:style wave :color "#87D700") :inherit unspecified :foreground unspecified :background unspecified)) (((class color) (min-colors 89)) (:foreground "#6B8E23" :background "#B3EE3A"))))
 '(flymake-warnline ((((supports :underline (:style wave)) (class color) (min-colors 89)) (:underline (:style wave :color "#CDC673") :inherit unspecified :foreground unspecified :background unspecified)) (((class color) (min-colors 89)) (:foreground "#968B26" :background "#FFF68F" :weight bold :underline t))))
 '(flycheck-error ((((supports :underline (:style wave)) (class color) (min-colors 89)) (:underline (:style wave :color "#FF1493") :inherit unspecified)) (((class color) (min-colors 89)) (:foreground "#5F0000" :background "#EE6AA7" :weight bold :underline t))))
 '(flycheck-warning ((((supports :underline (:style wave)) (class color) (min-colors 89)) (:underline (:style wave :color "#CDC673") :inherit unspecified)) (((class color) (min-colors 89)) (:foreground "#968B26" :background "#FFF68F" :weight bold :underline t))))
 '(flycheck-info ((((supports :underline (:style wave)) (class color) (min-colors 89)) (:underline (:style wave :color "#5FD7FF") :inherit unspecified)) (((class color) (min-colors 89)) (:foreground "#21889B" :background "#8DE6F7" :weight bold :underline t))))
 '(flycheck-fringe-error ((((class color) (min-colors 89)) (:foreground "#5F0000" :background "#EE6AA7" :weight bold))))
 '(flycheck-fringe-warning ((((class color) (min-colors 89)) (:foreground "#968B26" :background "#FFF68F" :weight bold))))
 '(flycheck-fringe-info ((((class color) (min-colors 89)) (:foreground "#21889B" :background "#8DE6F7" :weight bold))))
 '(flyspell-duplicate ((((supports :underline (:style wave)) (class color) (min-colors 89)) (:underline (:style wave :color "#CDC673") :inherit unspecified)) (((class color) (min-colors 89)) (:foreground "#CDC673" :weight bold :underline t))))
 '(flyspell-incorrect ((((supports :underline (:style wave)) (class color) (min-colors 89)) (:underline (:style wave :color "#FF1493") :inherit unspecified)) (((class color) (min-colors 89)) (:foreground "#FF1493" :weight bold :underline t))))
 '(git-gutter:added ((((class color) (min-colors 89)) (:background "#87D700" :foreground "#1B1E1C" :weight bold))))
 '(git-gutter:deleted ((((class color) (min-colors 89)) (:background "#FF1493" :foreground "#1B1E1C" :weight bold))))
 '(git-gutter:modified ((((class color) (min-colors 89)) (:background "#5FD7FF" :foreground "#1B1E1C" :weight bold))))
 '(git-gutter:unchanged ((((class color) (min-colors 89)) (:background "#303030" :foreground "#1B1E1C" :weight bold))))
 '(git-gutter-fr:added ((((class color) (min-colors 89)) (:foreground "#87D700" :weight bold))))
 '(git-gutter-fr:deleted ((((class color) (min-colors 89)) (:foreground "#FF1493" :weight bold))))
 '(git-gutter-fr:modified ((((class color) (min-colors 89)) (:foreground "#5FD7FF" :weight bold))))
 '(git-gutter+-added ((((class color) (min-colors 89)) (:background "#87D700" :foreground "#1B1E1C" :weight bold))))
 '(git-gutter+-deleted ((((class color) (min-colors 89)) (:background "#FF1493" :foreground "#1B1E1C" :weight bold))))
 '(git-gutter+-modified ((((class color) (min-colors 89)) (:background "#5FD7FF" :foreground "#1B1E1C" :weight bold))))
 '(git-gutter+-unchanged ((((class color) (min-colors 89)) (:background "#303030" :foreground "#1B1E1C" :weight bold))))
 '(git-gutter-fr+-added ((((class color) (min-colors 89)) (:foreground "#87D700" :weight bold))))
 '(git-gutter-fr+-deleted ((((class color) (min-colors 89)) (:foreground "#FF1493" :weight bold))))
 '(git-gutter-fr+-modified ((((class color) (min-colors 89)) (:foreground "#5FD7FF" :weight bold))))
 '(guide-key/highlight-command-face ((((class color) (min-colors 89)) (:foreground "#5FD7FF"))))
 '(guide-key/key-face ((((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(guide-key/prefix-command-face ((((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(gnus-group-mail-1 ((((class color) (min-colors 89)) (:weight bold :inherit gnus-group-mail-1-empty))))
 '(gnus-group-mail-1-empty ((((class color) (min-colors 89)) (:inherit gnus-group-news-1-empty))))
 '(gnus-group-mail-2 ((((class color) (min-colors 89)) (:weight bold :inherit gnus-group-mail-2-empty))))
 '(gnus-group-mail-2-empty ((((class color) (min-colors 89)) (:inherit gnus-group-news-2-empty))))
 '(gnus-group-mail-3 ((((class color) (min-colors 89)) (:weight bold :inherit gnus-group-mail-3-empty))))
 '(gnus-group-mail-3-empty ((((class color) (min-colors 89)) (:inherit gnus-group-news-3-empty))))
 '(gnus-group-mail-low ((((class color) (min-colors 89)) (:weight bold :inherit gnus-group-mail-low-empty))))
 '(gnus-group-mail-low-empty ((((class color) (min-colors 89)) (:inherit gnus-group-news-low-empty))))
 '(gnus-group-news-1 ((((class color) (min-colors 89)) (:weight bold :inherit gnus-group-news-1-empty))))
 '(gnus-group-news-2 ((((class color) (min-colors 89)) (:weight bold :inherit gnus-group-news-2-empty))))
 '(gnus-group-news-3 ((((class color) (min-colors 89)) (:weight bold :inherit gnus-group-news-3-empty))))
 '(gnus-group-news-4 ((((class color) (min-colors 89)) (:weight bold :inherit gnus-group-news-4-empty))))
 '(gnus-group-news-5 ((((class color) (min-colors 89)) (:weight bold :inherit gnus-group-news-5-empty))))
 '(gnus-group-news-6 ((((class color) (min-colors 89)) (:weight bold :inherit gnus-group-news-6-empty))))
 '(gnus-group-news-low ((((class color) (min-colors 89)) (:weight bold :inherit gnus-group-news-low-empty))))
 '(gnus-header-content ((((class color) (min-colors 89)) (:inherit message-header-other))))
 '(gnus-header-from ((((class color) (min-colors 89)) (:inherit message-header-other))))
 '(gnus-header-name ((((class color) (min-colors 89)) (:inherit message-header-name))))
 '(gnus-header-newsgroups ((((class color) (min-colors 89)) (:inherit message-header-other))))
 '(gnus-header-subject ((((class color) (min-colors 89)) (:inherit message-header-subject))))
 '(gnus-summary-cancelled ((((class color) (min-colors 89)) (:foreground "#FF8C00"))))
 '(gnus-summary-high-ancient ((((class color) (min-colors 89)) (:foreground "#5FD7FF" :weight bold))))
 '(gnus-summary-high-read ((((class color) (min-colors 89)) (:foreground "#87D700" :weight bold))))
 '(gnus-summary-high-ticked ((((class color) (min-colors 89)) (:foreground "#FF8C00" :weight bold))))
 '(gnus-summary-high-unread ((((class color) (min-colors 89)) (:foreground "#F5F5F5" :weight bold))))
 '(gnus-summary-low-ancient ((((class color) (min-colors 89)) (:foreground "#5FD7FF"))))
 '(gnus-summary-low-read ((t (:foreground "#87D700"))))
 '(gnus-summary-low-ticked ((((class color) (min-colors 89)) (:foreground "#FF8C00"))))
 '(gnus-summary-low-unread ((((class color) (min-colors 89)) (:foreground "#F5F5F5"))))
 '(gnus-summary-normal-ancient ((((class color) (min-colors 89)) (:foreground "#5FD7FF"))))
 '(gnus-summary-normal-read ((((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(gnus-summary-normal-ticked ((((class color) (min-colors 89)) (:foreground "#FF8C00"))))
 '(gnus-summary-normal-unread ((((class color) (min-colors 89)) (:foreground "#F5F5F5"))))
 '(gnus-summary-selected ((((class color) (min-colors 89)) (:foreground "#CDC673" :weight bold))))
 '(gnus-cite-1 ((((class color) (min-colors 89)) (:foreground "#5FD7FF"))))
 '(gnus-cite-2 ((((class color) (min-colors 89)) (:foreground "#5FD7FF"))))
 '(gnus-cite-3 ((((class color) (min-colors 89)) (:foreground "#5FD7FF"))))
 '(gnus-cite-4 ((((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(gnus-cite-5 ((((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(gnus-cite-6 ((((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(gnus-cite-7 ((((class color) (min-colors 89)) (:foreground "#FF1493"))))
 '(gnus-cite-8 ((((class color) (min-colors 89)) (:foreground "#FF1493"))))
 '(gnus-cite-9 ((((class color) (min-colors 89)) (:foreground "#FF1493"))))
 '(gnus-cite-10 ((((class color) (min-colors 89)) (:foreground "#CDC673"))))
 '(gnus-cite-11 ((((class color) (min-colors 89)) (:foreground "#CDC673"))))
 '(gnus-group-news-1-empty ((((class color) (min-colors 89)) (:foreground "#CDC673"))))
 '(gnus-group-news-2-empty ((((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(gnus-group-news-3-empty ((((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(gnus-group-news-4-empty ((((class color) (min-colors 89)) (:foreground "#5FD7FF"))))
 '(gnus-group-news-5-empty ((((class color) (min-colors 89)) (:foreground "#5FD7FF"))))
 '(gnus-group-news-6-empty ((((class color) (min-colors 89)) (:foreground "#8DE6F7"))))
 '(gnus-group-news-low-empty ((((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(gnus-signature ((((class color) (min-colors 89)) (:foreground "#CDC673"))))
 '(gnus-x-face ((((class color) (min-colors 89)) (:background "#F5F5F5" :foreground "#1B1E1C"))))
 '(helm-apt-deinstalled ((((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(helm-apt-installed ((((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(helm-bookmark-directory ((((class color) (min-colors 89)) (:inherit helm-ff-directory))))
 '(helm-bookmark-file ((((class color) (min-colors 89)) (:foreground "#F5F5F5"))))
 '(helm-bookmark-gnus ((((class color) (min-colors 89)) (:foreground "#5FFFFF"))))
 '(helm-bookmark-info ((((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(helm-bookmark-man ((((class color) (min-colors 89)) (:foreground "#AF87FF"))))
 '(helm-bookmark-w3m ((((class color) (min-colors 89)) (:foreground "#CDC673"))))
 '(helm-bookmarks-su ((((class color) (min-colors 89)) (:foreground "#FF8C00"))))
 '(helm-buffer-not-saved ((((class color) (min-colors 89)) (:foreground "#FF8C00"))))
 '(helm-buffer-saved-out ((((class color) (min-colors 89)) (:foreground "#FF1493" :background "#1B1E1C" :inverse-video t))))
 '(helm-buffer-size ((((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(helm-candidate-number ((((class color) (min-colors 89)) (:background "#303030" :foreground "#FFFAFA" :bold t))))
 '(helm-ff-directory ((((class color) (min-colors 89)) (:background "#1B1E1C" :foreground "#5FD7FF"))))
 '(helm-ff-executable ((((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(helm-ff-file ((((class color) (min-colors 89)) (:background "#1B1E1C" :foreground "#F5F5F5"))))
 '(helm-ff-invalid-symlink ((((class color) (min-colors 89)) (:background "#1B1E1C" :foreground "#FF8C00" :slant italic))))
 '(helm-ff-prefix ((((class color) (min-colors 89)) (:background "#CDC673" :foreground "#1B1E1C"))))
 '(helm-ff-symlink ((((class color) (min-colors 89)) (:foreground "#5FFFFF"))))
 '(helm-grep-file ((((class color) (min-colors 89)) (:foreground "#5FFFFF" :underline t))))
 '(helm-grep-finish ((((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(helm-grep-lineno ((((class color) (min-colors 89)) (:foreground "#FF8C00"))))
 '(helm-grep-match ((((class color) (min-colors 89)) (:inherit match))))
 '(helm-grep-running ((((class color) (min-colors 89)) (:foreground "#FF1493"))))
 '(helm-header ((((class color) (min-colors 89)) (:inherit header-line))))
 '(helm-lisp-completion-info ((((class color) (min-colors 89)) (:foreground "#F5F5F5"))))
 '(helm-lisp-show-completion ((((class color) (min-colors 89)) (:foreground "#CDC673" :background "#303030" :bold t))))
 '(helm-M-x-key ((((class color) (min-colors 89)) (:foreground "#FF8C00" :underline t))))
 '(helm-moccur-buffer ((((class color) (min-colors 89)) (:foreground "#5FFFFF" :underline t))))
 '(helm-match ((((class color) (min-colors 89)) (:inherit match))))
 '(helm-selection ((((class color) (min-colors 89)) (:background "#303030" :underline t))))
 '(helm-selection-line ((((class color) (min-colors 89)) (:background "#303030" :foreground "#FFFAFA" :underline nil))))
 '(helm-separator ((((class color) (min-colors 89)) (:foreground "#FF1493"))))
 '(helm-source-header ((((class color) (min-colors 89)) (:background "#8DE6F7" :foreground "#1B1E1C" :underline nil))))
 '(helm-swoop-target-line-face ((((class color) (min-colors 89)) (:background "#303030"))))
 '(helm-swoop-target-line-block-face ((((class color) (min-colors 89)) (:background "#303030"))))
 '(helm-swoop-target-word-face ((((class color) (min-colors 89)) (:foreground "#D700D7" :background unspecified))))
 '(helm-time-zone-current ((((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(helm-time-zone-home ((((class color) (min-colors 89)) (:foreground "#FF1493"))))
 '(helm-visible-mark ((((class color) (min-colors 89)) (:background "#1B1E1C" :foreground "#D700D7" :bold t))))
 '(helm-ls-git-modified-not-staged-face ((((class color) (min-colors 89)) :foreground "#5FD7FF")))
 '(helm-ls-git-modified-and-staged-face ((((class color) (min-colors 89)) :foreground "#8DE6F7")))
 '(helm-ls-git-renamed-modified-face ((((class color) (min-colors 89)) :foreground "#8DE6F7")))
 '(helm-ls-git-untracked-face ((((class color) (min-colors 89)) :foreground "#FF8C00")))
 '(helm-ls-git-added-copied-face ((((class color) (min-colors 89)) :foreground "#87D700")))
 '(helm-ls-git-deleted-not-staged-face ((((class color) (min-colors 89)) :foreground "#FF1493")))
 '(helm-ls-git-deleted-and-staged-face ((((class color) (min-colors 89)) :foreground "#EE6AA7")))
 '(helm-ls-git-conflict-face ((((class color) (min-colors 89)) :foreground "#CDC673")))
 '(hi-yellow ((((class color) (min-colors 89)) (:foreground "#FFF68F" :background "#968B26"))))
 '(hi-pink ((((class color) (min-colors 89)) (:foreground "#FE87F4" :background "#A41F99"))))
 '(hi-green ((((class color) (min-colors 89)) (:foreground "#B3EE3A" :background "#6B8E23"))))
 '(hi-blue ((((class color) (min-colors 89)) (:foreground "#8DE6F7" :background "#21889B"))))
 '(hi-black-b ((((class color) (min-colors 89)) (:foreground "#FFFAFA" :background "#1B1E1C" :weight bold))))
 '(hi-blue-b ((((class color) (min-colors 89)) (:foreground "#8DE6F7" :weight bold))))
 '(hi-green-b ((((class color) (min-colors 89)) (:foreground "#B3EE3A" :weight bold))))
 '(hi-red-b ((((class color) (min-colors 89)) (:foreground "#FF1493" :weight bold))))
 '(hi-black-hb ((((class color) (min-colors 89)) (:foreground "#FFFAFA" :background "#1B1E1C" :weight bold))))
 '(highlight-changes ((((class color) (min-colors 89)) (:foreground "#FF8C00"))))
 '(highlight-changes-delete ((((class color) (min-colors 89)) (:foreground "#FF1493" :underline t))))
 '(highlight-indentation-face ((((class color) (min-colors 89)) (:background "#303030"))))
 '(highlight-indentation-current-column-face ((((class color) (min-colors 89)) (:background "#303030"))))
 '(hl-line ((((class color) (min-colors 89)) (:background "#212121" :inherit t))))
 '(hl-line-face ((((class color) (min-colors 89)) (:background "#212121" :inherit t))))
 '(ido-first-match ((((class color) (min-colors 89)) (:foreground "#CDC673" :weight normal))))
 '(ido-only-match ((((class color) (min-colors 89)) (:foreground "#1B1E1C" :background "#CDC673" :weight normal))))
 '(ido-subdir ((((class color) (min-colors 89)) (:foreground "#5FD7FF"))))
 '(ido-incomplete-regexp ((((class color) (min-colors 89)) (:foreground "#FF1493" :weight bold))))
 '(ido-indicator ((((class color) (min-colors 89)) (:background "#FF1493" :foreground "#1B1E1C" :width condensed))))
 '(ido-virtual ((((class color) (min-colors 89)) (:foreground "#5FFFFF"))))
 '(jabber-activity-face ((((class color) (min-colors 89)) (:weight bold :foreground "#FF1493"))))
 '(jabber-activity-personal-face ((((class color) (min-colors 89)) (:weight bold :foreground "#5FD7FF"))))
 '(jabber-chat-error ((((class color) (min-colors 89)) (:weight bold :foreground "#FF1493"))))
 '(jabber-chat-prompt-foreign ((((class color) (min-colors 89)) (:weight bold :foreground "#FF1493"))))
 '(jabber-chat-prompt-local ((((class color) (min-colors 89)) (:weight bold :foreground "#5FD7FF"))))
 '(jabber-chat-prompt-system ((((class color) (min-colors 89)) (:weight bold :foreground "#87D700"))))
 '(jabber-chat-text-foreign ((((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(jabber-chat-text-local ((((class color) (min-colors 89)) (:foreground "#F5F5F5"))))
 '(jabber-chat-rare-time-face ((((class color) (min-colors 89)) (:underline t :foreground "#87D700"))))
 '(jabber-roster-user-away ((((class color) (min-colors 89)) (:slant italic :foreground "#87D700"))))
 '(jabber-roster-user-chatty ((((class color) (min-colors 89)) (:weight bold :foreground "#FF8C00"))))
 '(jabber-roster-user-dnd ((((class color) (min-colors 89)) (:slant italic :foreground "#FF1493"))))
 '(jabber-roster-user-error ((((class color) (min-colors 89)) (:weight light :slant italic :foreground "#FF1493"))))
 '(jabber-roster-user-offline ((((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(jabber-roster-user-online ((((class color) (min-colors 89)) (:weight bold :foreground "#5FD7FF"))))
 '(jabber-roster-user-xa ((((class color) (min-colors 89)) (:slant italic :foreground "#D700D7"))))
 '(js2-error ((((class color) (min-colors 89)) (:foreground "#FF1493"))))
 '(js2-external-variable ((((class color) (min-colors 89)) (:foreground "#FF8C00"))))
 '(js2-function-param ((((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(js2-instance-member ((((class color) (min-colors 89)) (:foreground "#D700D7"))))
 '(js2-jsdoc-html-tag-delimiter ((((class color) (min-colors 89)) (:foreground "#5FFFFF"))))
 '(js2-jsdoc-html-tag-name ((((class color) (min-colors 89)) (:foreground "#FF8C00"))))
 '(js2-jsdoc-tag ((((class color) (min-colors 89)) (:foreground "#5FFFFF"))))
 '(js2-jsdoc-type ((((class color) (min-colors 89)) (:foreground "#5FD7FF"))))
 '(js2-jsdoc-value ((((class color) (min-colors 89)) (:foreground "#AF87FF"))))
 '(js2-magic-paren ((((class color) (min-colors 89)) (:underline t))))
 '(js2-private-function-call ((((class color) (min-colors 89)) (:foreground "#CDC673"))))
 '(js2-private-member ((((class color) (min-colors 89)) (:foreground "#5FD7FF"))))
 '(js2-warning ((((class color) (min-colors 89)) (:underline "#FF8C00"))))
 '(jedi:highlight-function-argument ((((class color) (min-colors 89)) (:inherit bold))))
 '(linum ((((class color) (min-colors 89)) (:foreground "#8B8878" :background "#1B1E1C"))))
 '(lusty-directory-face ((((class color) (min-colors 89)) (:inherit dired-directory))))
 '(lusty-file-face ((((class color) (min-colors 89)) nil)))
 '(lusty-match-face ((((class color) (min-colors 89)) (:inherit ido-first-match))))
 '(lusty-slash-face ((((class color) (min-colors 89)) (:foreground "#5FFFFF" :weight bold))))
 '(magit-section-title ((((class color) (min-colors 89)) (:foreground "#CDC673" :weight bold))))
 '(magit-branch ((((class color) (min-colors 89)) (:foreground "#FF8C00" :weight bold))))
 '(magit-item-highlight ((((class color) (min-colors 89)) (:background "#303030" :weight unspecified))))
 '(magit-log-author ((((class color) (min-colors 89)) (:foreground "#5FFFFF"))))
 '(magit-log-graph ((((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(magit-log-head-label-bisect-bad ((((class color) (min-colors 89)) (:background "#5F0000" :foreground "#EE6AA7" :box 1))))
 '(magit-log-head-label-bisect-good ((((class color) (min-colors 89)) (:background "#6B8E23" :foreground "#B3EE3A" :box 1))))
 '(magit-log-head-label-default ((((class color) (min-colors 89)) (:background "#303030" :box 1))))
 '(magit-log-head-label-local ((((class color) (min-colors 89)) (:background "#8DE6F7" :foreground "#21889B" :box 1))))
 '(magit-log-head-label-patches ((((class color) (min-colors 89)) (:background "#EE6AA7" :foreground "#5F0000" :box 1))))
 '(magit-log-head-label-remote ((((class color) (min-colors 89)) (:background "#B3EE3A" :foreground "#6B8E23" :box 1))))
 '(magit-log-head-label-tags ((((class color) (min-colors 89)) (:background "#FFF68F" :foreground "#968B26" :box 1))))
 '(magit-log-sha1 ((((class color) (min-colors 89)) (:foreground "#CDC673"))))
 '(markdown-header-face ((((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(markdown-header-face-1 ((((class color) (min-colors 89)) (:inherit markdown-header-face :height 1.3))))
 '(markdown-header-face-2 ((((class color) (min-colors 89)) (:inherit markdown-header-face :height 1.2))))
 '(markdown-header-face-3 ((((class color) (min-colors 89)) (:inherit markdown-header-face :height 1.15))))
 '(markdown-header-face-4 ((((class color) (min-colors 89)) (:inherit markdown-header-face :height 1.1))))
 '(markdown-header-face-5 ((((class color) (min-colors 89)) (:inherit markdown-header-face))))
 '(markdown-header-face-6 ((((class color) (min-colors 89)) (:inherit markdown-header-face))))
 '(message-cited-text ((((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(message-header-name ((((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(message-header-other ((((class color) (min-colors 89)) (:foreground "#F5F5F5" :weight normal))))
 '(message-header-to ((((class color) (min-colors 89)) (:foreground "#F5F5F5" :weight normal))))
 '(message-header-cc ((((class color) (min-colors 89)) (:foreground "#F5F5F5" :weight normal))))
 '(message-header-newsgroups ((((class color) (min-colors 89)) (:foreground "#CDC673" :weight bold))))
 '(message-header-subject ((((class color) (min-colors 89)) (:foreground "#5FFFFF" :weight normal))))
 '(message-header-xheader ((((class color) (min-colors 89)) (:foreground "#5FFFFF"))))
 '(message-mml ((((class color) (min-colors 89)) (:foreground "#CDC673" :weight bold))))
 '(message-separator ((((class color) (min-colors 89)) (:foreground "#8B8878" :slant italic))))
 '(mew-face-header-subject ((((class color) (min-colors 89)) (:foreground "#FF8C00"))))
 '(mew-face-header-from ((((class color) (min-colors 89)) (:foreground "#CDC673"))))
 '(mew-face-header-date ((((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(mew-face-header-to ((((class color) (min-colors 89)) (:foreground "#FF1493"))))
 '(mew-face-header-key ((((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(mew-face-header-private ((((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(mew-face-header-important ((((class color) (min-colors 89)) (:foreground "#5FD7FF"))))
 '(mew-face-header-marginal ((((class color) (min-colors 89)) (:foreground "#F5F5F5" :weight bold))))
 '(mew-face-header-warning ((((class color) (min-colors 89)) (:foreground "#FF1493"))))
 '(mew-face-header-xmew ((((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(mew-face-header-xmew-bad ((((class color) (min-colors 89)) (:foreground "#FF1493"))))
 '(mew-face-body-url ((((class color) (min-colors 89)) (:foreground "#FF8C00"))))
 '(mew-face-body-comment ((((class color) (min-colors 89)) (:foreground "#F5F5F5" :slant italic))))
 '(mew-face-body-cite1 ((((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(mew-face-body-cite2 ((((class color) (min-colors 89)) (:foreground "#5FD7FF"))))
 '(mew-face-body-cite3 ((((class color) (min-colors 89)) (:foreground "#FF8C00"))))
 '(mew-face-body-cite4 ((((class color) (min-colors 89)) (:foreground "#CDC673"))))
 '(mew-face-body-cite5 ((((class color) (min-colors 89)) (:foreground "#FF1493"))))
 '(mew-face-mark-review ((((class color) (min-colors 89)) (:foreground "#5FD7FF"))))
 '(mew-face-mark-escape ((((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(mew-face-mark-delete ((((class color) (min-colors 89)) (:foreground "#FF1493"))))
 '(mew-face-mark-unlink ((((class color) (min-colors 89)) (:foreground "#CDC673"))))
 '(mew-face-mark-refile ((((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(mew-face-mark-unread ((((class color) (min-colors 89)) (:foreground "#FF1493"))))
 '(mew-face-eof-message ((((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(mew-face-eof-part ((((class color) (min-colors 89)) (:foreground "#CDC673"))))
 '(mingus-directory-face ((((class color) (min-colors 89)) (:foreground "#5FD7FF"))))
 '(mingus-pausing-face ((((class color) (min-colors 89)) (:foreground "#D700D7"))))
 '(mingus-playing-face ((((class color) (min-colors 89)) (:foreground "#5FFFFF"))))
 '(mingus-playlist-face ((((class color) (min-colors 89)) (:foreground "#5FFFFF"))))
 '(mingus-song-file-face ((((class color) (min-colors 89)) (:foreground "#CDC673"))))
 '(mingus-stopped-face ((((class color) (min-colors 89)) (:foreground "#FF1493"))))
 '(moccur-current-line-face ((((class color) (min-colors 89)) (:underline t))))
 '(moccur-edit-done-face ((((class color) (min-colors 89)) (:foreground "#8B8878" :background "#1B1E1C" :slant italic))))
 '(moccur-edit-face ((((class color) (min-colors 89)) (:background "#CDC673" :foreground "#1B1E1C"))))
 '(moccur-edit-file-face ((((class color) (min-colors 89)) (:background "#303030"))))
 '(moccur-edit-reject-face ((((class color) (min-colors 89)) (:foreground "#FF1493"))))
 '(moccur-face ((((class color) (min-colors 89)) (:background "#303030" :foreground "#FFFAFA" :weight bold))))
 '(search-buffers-face ((((class color) (min-colors 89)) (:background "#303030" :foreground "#FFFAFA" :weight bold))))
 '(search-buffers-header-face ((((class color) (min-colors 89)) (:background "#303030" :foreground "#CDC673" :weight bold))))
 '(mu4e-cited-1-face ((((class color) (min-colors 89)) (:foreground "#87D700" :slant italic :weight normal))))
 '(mu4e-cited-2-face ((((class color) (min-colors 89)) (:foreground "#5FD7FF" :slant italic :weight normal))))
 '(mu4e-cited-3-face ((((class color) (min-colors 89)) (:foreground "#FF8C00" :slant italic :weight normal))))
 '(mu4e-cited-4-face ((((class color) (min-colors 89)) (:foreground "#CDC673" :slant italic :weight normal))))
 '(mu4e-cited-5-face ((((class color) (min-colors 89)) (:foreground "#5FFFFF" :slant italic :weight normal))))
 '(mu4e-cited-6-face ((((class color) (min-colors 89)) (:foreground "#87D700" :slant italic :weight normal))))
 '(mu4e-cited-7-face ((((class color) (min-colors 89)) (:foreground "#5FD7FF" :slant italic :weight normal))))
 '(mu4e-flagged-face ((((class color) (min-colors 89)) (:foreground "#D700D7" :weight bold))))
 '(mu4e-view-url-number-face ((((class color) (min-colors 89)) (:foreground "#CDC673" :weight normal))))
 '(mu4e-warning-face ((((class color) (min-colors 89)) (:foreground "#FF1493" :slant normal :weight bold))))
 '(mu4e-header-highlight-face ((((class color) (min-colors 89)) (:inherit unspecified :foreground unspecified :background "#303030" :underline "#FFFAFA" :weight normal))))
 '(mu4e-draft-face ((((class color) (min-colors 89)) (:inherit font-lock-string-face))))
 '(mu4e-footer-face ((((class color) (min-colors 89)) (:inherit font-lock-comment-face))))
 '(mu4e-forwarded-face ((((class color) (min-colors 89)) (:inherit font-lock-builtin-face :weight normal))))
 '(mu4e-header-face ((((class color) (min-colors 89)) (:inherit default))))
 '(mu4e-header-marks-face ((((class color) (min-colors 89)) (:inherit font-lock-preprocessor-face))))
 '(mu4e-header-title-face ((((class color) (min-colors 89)) (:inherit font-lock-type-face))))
 '(mu4e-highlight-face ((((class color) (min-colors 89)) (:inherit font-lock-pseudo-keyword-face :weight bold))))
 '(mu4e-moved-face ((((class color) (min-colors 89)) (:inherit font-lock-comment-face :slant italic))))
 '(mu4e-ok-face ((((class color) (min-colors 89)) (:inherit font-lock-comment-face :slant normal :weight bold))))
 '(mu4e-replied-face ((((class color) (min-colors 89)) (:inherit font-lock-builtin-face :weight normal))))
 '(mu4e-system-face ((((class color) (min-colors 89)) (:inherit font-lock-comment-face :slant italic))))
 '(mu4e-title-face ((((class color) (min-colors 89)) (:inherit font-lock-type-face :weight bold))))
 '(mu4e-trashed-face ((((class color) (min-colors 89)) (:inherit font-lock-comment-face :strike-through t))))
 '(mu4e-unread-face ((((class color) (min-colors 89)) (:inherit font-lock-keyword-face :weight bold))))
 '(mu4e-view-attach-number-face ((((class color) (min-colors 89)) (:inherit font-lock-variable-name-face :weight bold))))
 '(mu4e-view-contact-face ((((class color) (min-colors 89)) (:foreground "#F5F5F5" :weight normal))))
 '(mu4e-view-header-key-face ((((class color) (min-colors 89)) (:inherit message-header-name :weight normal))))
 '(mu4e-view-header-value-face ((((class color) (min-colors 89)) (:foreground "#5FFFFF" :weight normal :slant normal))))
 '(mu4e-view-link-face ((((class color) (min-colors 89)) (:inherit link))))
 '(mu4e-view-special-header-value-face ((((class color) (min-colors 89)) (:foreground "#5FD7FF" :weight normal :underline nil))))
 '(mumamo-background-chunk-submode1 ((((class color) (min-colors 89)) (:background "#303030"))))
 '(nav-face-heading ((((class color) (min-colors 89)) (:foreground "#CDC673"))))
 '(nav-face-button-num ((((class color) (min-colors 89)) (:foreground "#5FFFFF"))))
 '(nav-face-dir ((((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(nav-face-hdir ((((class color) (min-colors 89)) (:foreground "#FF1493"))))
 '(nav-face-file ((((class color) (min-colors 89)) (:foreground "#F5F5F5"))))
 '(nav-face-hfile ((((class color) (min-colors 89)) (:foreground "#FF1493"))))
 '(nav-flash-face ((((class color) (min-colors 89)) (:background "#303030"))))
 '(org-agenda-structure ((((class color) (min-colors 89)) (:foreground "#FFFAFA" :background "#303030" :weight bold :slant normal :inverse-video nil :height 1.1 :underline nil :box (:line-width 2 :color "#1B1E1C")))))
 '(org-agenda-calendar-event ((((class color) (min-colors 89)) (:foreground "#FFFAFA"))))
 '(org-agenda-calendar-sexp ((((class color) (min-colors 89)) (:foreground "#F5F5F5" :slant italic))))
 '(org-agenda-date ((((class color) (min-colors 89)) (:foreground "#8B8878" :background "#1B1E1C" :weight normal :inverse-video nil :overline nil :slant normal :height 1.0 :box (:line-width 2 :color "#1B1E1C")))))
 '(org-agenda-date-weekend ((((class color) (min-colors 89)) (:inherit org-agenda-date :inverse-video nil :background unspecified :foreground "#8B8878" :weight unspecified :underline t :overline nil :box unspecified))))
 '(org-agenda-date-today ((((class color) (min-colors 89)) (:inherit org-agenda-date :inverse-video t :weight bold :underline unspecified :overline nil :box unspecified :foreground "#5FD7FF" :background "#1B1E1C"))))
 '(org-agenda-done ((((class color) (min-colors 89)) (:foreground "#8B8878" :slant italic))))
 '(org-archived ((((class color) (min-colors 89)) (:foreground "#8B8878" :weight normal))))
 '(org-block ((((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(org-block-begin-line ((((class color) (min-colors 89)) (:foreground "#8B8878" :slant italic))))
 '(org-checkbox ((((class color) (min-colors 89)) (:background "#1B1E1C" :foreground "#F5F5F5" :box (:line-width 1 :style released-button)))))
 '(org-code ((((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(org-date ((((class color) (min-colors 89)) (:foreground "#5FD7FF" :underline t))))
 '(org-done ((((class color) (min-colors 89)) (:weight bold :foreground "#87D700"))))
 '(org-ellipsis ((((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(org-formula ((((class color) (min-colors 89)) (:foreground "#CDC673"))))
 '(org-headline-done ((((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(org-hide ((((class color) (min-colors 89)) (:foreground "#1B1E1C"))))
 '(org-level-1 ((((class color) (min-colors 89)) (:inherit variable-pitch :height 1.3 :foreground "#FF8C00"))))
 '(org-level-2 ((((class color) (min-colors 89)) (:inherit variable-pitch :height 1.2 :foreground "#87D700"))))
 '(org-level-3 ((((class color) (min-colors 89)) (:inherit variable-pitch :height 1.15 :foreground "#5FD7FF"))))
 '(org-level-4 ((((class color) (min-colors 89)) (:inherit variable-pitch :height 1.1 :foreground "#CDC673"))))
 '(org-level-5 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#5FFFFF"))))
 '(org-level-6 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#87D700"))))
 '(org-level-7 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#FF1493"))))
 '(org-level-8 ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#5FD7FF"))))
 '(org-link ((((class color) (min-colors 89)) (:foreground "#CDC673" :underline t))))
 '(org-sexp-date ((((class color) (min-colors 89)) (:foreground "#AF87FF"))))
 '(org-scheduled ((((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(org-scheduled-previously ((((class color) (min-colors 89)) (:foreground "#5FFFFF"))))
 '(org-scheduled-today ((((class color) (min-colors 89)) (:foreground "#5FD7FF" :weight normal))))
 '(org-special-keyword ((((class color) (min-colors 89)) (:foreground "#8B8878" :weight bold))))
 '(org-table ((((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(org-tag ((((class color) (min-colors 89)) (:weight bold))))
 '(org-time-grid ((((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(org-todo ((((class color) (min-colors 89)) (:foreground "#FF1493" :weight bold))))
 '(org-upcoming-deadline ((((class color) (min-colors 89)) (:foreground "#CDC673" :weight normal :underline nil))))
 '(org-warning ((((class color) (min-colors 89)) (:foreground "#FF8C00" :weight normal :underline nil))))
 '(org-habit-clear-face ((((class color) (min-colors 89)) (:background "#8DE6F7" :foreground "#21889B"))))
 '(org-habit-clear-future-face ((((class color) (min-colors 89)) (:background "#8DE6F7"))))
 '(org-habit-ready-face ((((class color) (min-colors 89)) (:background "#B3EE3A" :foreground "#87D700"))))
 '(org-habit-ready-future-face ((((class color) (min-colors 89)) (:background "#B3EE3A"))))
 '(org-habit-alert-face ((((class color) (min-colors 89)) (:background "#CDC673" :foreground "#FFF68F"))))
 '(org-habit-alert-future-face ((((class color) (min-colors 89)) (:background "#FFF68F"))))
 '(org-habit-overdue-face ((((class color) (min-colors 89)) (:background "#FF1493" :foreground "#EE6AA7"))))
 '(org-habit-overdue-future-face ((((class color) (min-colors 89)) (:background "#EE6AA7"))))
 '(org-agenda-dimmed-todo-face ((((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(org-agenda-restriction-lock ((((class color) (min-colors 89)) (:background "#CDC673"))))
 '(org-clock-overlay ((((class color) (min-colors 89)) (:background "#CDC673"))))
 '(org-column ((((class color) (min-colors 89)) (:background "#303030" :strike-through nil :underline nil :slant normal :weight normal :inherit default))))
 '(org-column-title ((((class color) (min-colors 89)) (:background "#303030" :underline t :weight bold))))
 '(org-date-selected ((((class color) (min-colors 89)) (:foreground "#FF1493" :inverse-video t))))
 '(org-document-info ((((class color) (min-colors 89)) (:foreground "#F5F5F5"))))
 '(org-document-title ((((class color) (min-colors 89)) (:foreground "#FFFAFA" :weight bold :height 1.3))))
 '(org-drawer ((((class color) (min-colors 89)) (:foreground "#5FFFFF"))))
 '(org-footnote ((((class color) (min-colors 89)) (:foreground "#D700D7" :underline t))))
 '(org-latex-and-export-specials ((((class color) (min-colors 89)) (:foreground "#FF8C00"))))
 '(org-mode-line-clock-overrun ((((class color) (min-colors 89)) (:inherit mode-line :background "#FF1493"))))
 '(outline-1 ((((class color) (min-colors 89)) (:inherit org-level-1))))
 '(outline-2 ((((class color) (min-colors 89)) (:inherit org-level-2))))
 '(outline-3 ((((class color) (min-colors 89)) (:inherit org-level-3))))
 '(outline-4 ((((class color) (min-colors 89)) (:inherit org-level-4))))
 '(outline-5 ((((class color) (min-colors 89)) (:inherit org-level-5))))
 '(outline-6 ((((class color) (min-colors 89)) (:inherit org-level-6))))
 '(outline-7 ((((class color) (min-colors 89)) (:inherit org-level-7))))
 '(outline-8 ((((class color) (min-colors 89)) (:inherit org-level-8))))
 '(paren-face ((((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(pretty-mode-symbol-face ((((class color) (min-colors 89)) (:foreground "#CDC673" :weight normal))))
 '(popup-face ((((class color) (min-colors 89)) (:background "#303030" :foreground "#F5F5F5"))))
 '(popup-isearch-match ((((class color) (min-colors 89)) (:background "#CDC673" :foreground "#1B1E1C"))))
 '(popup-menu-face ((((class color) (min-colors 89)) (:background "#303030" :foreground "#F5F5F5"))))
 '(popup-menu-mouse-face ((((class color) (min-colors 89)) (:background "#5FD7FF" :foreground "#F5F5F5"))))
 '(popup-menu-selection-face ((((class color) (min-colors 89)) (:background "#D700D7" :foreground "#1B1E1C"))))
 '(popup-scroll-bar-background-face ((((class color) (min-colors 89)) (:background "#8B8878"))))
 '(popup-scroll-bar-foreground-face ((((class color) (min-colors 89)) (:background "#FFFAFA"))))
 '(popup-tip-face ((((class color) (min-colors 89)) (:background "#303030" :foreground "#F5F5F5"))))
 '(powerline-active1 ((((class color) (min-colors 89)) (:background "#444444"))))
 '(powerline-active2 ((((class color) (min-colors 89)) (:background "#6c6c6c"))))
 '(powerline-inactive1 ((((class color) (min-colors 89)) (:background "#3a3a3a"))))
 '(powerline-inactive2 ((((class color) (min-colors 89)) (:background "#444444"))))
 '(rainbow-delimiters-depth-1-face ((((class color) (min-colors 89)) (:foreground "#5FFFFF"))))
 '(rainbow-delimiters-depth-2-face ((((class color) (min-colors 89)) (:foreground "#CDC673"))))
 '(rainbow-delimiters-depth-3-face ((((class color) (min-colors 89)) (:foreground "#5FD7FF"))))
 '(rainbow-delimiters-depth-4-face ((((class color) (min-colors 89)) (:foreground "#FF8C00"))))
 '(rainbow-delimiters-depth-5-face ((((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(rainbow-delimiters-depth-6-face ((((class color) (min-colors 89)) (:foreground "#CDC673"))))
 '(rainbow-delimiters-depth-7-face ((((class color) (min-colors 89)) (:foreground "#5FD7FF"))))
 '(rainbow-delimiters-depth-8-face ((((class color) (min-colors 89)) (:foreground "#FF8C00"))))
 '(rainbow-delimiters-depth-9-face ((((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(rainbow-delimiters-depth-10-face ((((class color) (min-colors 89)) (:foreground "#CDC673"))))
 '(rainbow-delimiters-depth-11-face ((((class color) (min-colors 89)) (:foreground "#5FD7FF"))))
 '(rainbow-delimiters-depth-12-face ((((class color) (min-colors 89)) (:foreground "#FF8C00"))))
 '(rainbow-delimiters-unmatched-face ((((class color) (min-colors 89)) (:foreground "#F5F5F5" :background "#1B1E1C" :inverse-video t))))
 '(erb-face ((((class color) (min-colors 89)) (:foreground "#FFFAFA" :background "#1B1E1C"))))
 '(erb-delim-face ((((class color) (min-colors 89)) (:foreground "#5FFFFF" :background "#1B1E1C"))))
 '(erb-exec-face ((((class color) (min-colors 89)) (:foreground "#FFFAFA" :background "#1B1E1C"))))
 '(erb-exec-delim-face ((((class color) (min-colors 89)) (:foreground "#5FFFFF" :background "#1B1E1C"))))
 '(erb-out-face ((((class color) (min-colors 89)) (:foreground "#FFFAFA" :background "#1B1E1C"))))
 '(erb-out-delim-face ((((class color) (min-colors 89)) (:foreground "#5FFFFF" :background "#1B1E1C"))))
 '(erb-comment-face ((((class color) (min-colors 89)) (:foreground "#FFFAFA" :background "#1B1E1C"))))
 '(erb-comment-delim-face ((((class color) (min-colors 89)) (:foreground "#5FFFFF" :background "#1B1E1C"))))
 '(rst-level-1-face ((((class color) (min-colors 89)) (:background "#CDC673" :foreground "#1B1E1C"))))
 '(rst-level-2-face ((((class color) (min-colors 89)) (:background "#5FFFFF" :foreground "#1B1E1C"))))
 '(rst-level-3-face ((((class color) (min-colors 89)) (:background "#5FD7FF" :foreground "#1B1E1C"))))
 '(rst-level-4-face ((((class color) (min-colors 89)) (:background "#AF87FF" :foreground "#1B1E1C"))))
 '(rst-level-5-face ((((class color) (min-colors 89)) (:background "#D700D7" :foreground "#1B1E1C"))))
 '(rst-level-6-face ((((class color) (min-colors 89)) (:background "#FF1493" :foreground "#1B1E1C"))))
 '(rpm-spec-dir-face ((((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(rpm-spec-doc-face ((((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(rpm-spec-ghost-face ((((class color) (min-colors 89)) (:foreground "#FF1493"))))
 '(rpm-spec-macro-face ((((class color) (min-colors 89)) (:foreground "#CDC673"))))
 '(rpm-spec-obsolete-tag-face ((((class color) (min-colors 89)) (:foreground "#FF1493"))))
 '(rpm-spec-package-face ((((class color) (min-colors 89)) (:foreground "#FF1493"))))
 '(rpm-spec-section-face ((((class color) (min-colors 89)) (:foreground "#CDC673"))))
 '(rpm-spec-tag-face ((((class color) (min-colors 89)) (:foreground "#5FD7FF"))))
 '(rpm-spec-var-face ((((class color) (min-colors 89)) (:foreground "#FF1493"))))
 '(sh-quoted-exec ((((class color) (min-colors 89)) (:foreground "#AF87FF" :weight bold))))
 '(sh-escaped-newline ((((class color) (min-colors 89)) (:foreground "#CDC673" :weight bold))))
 '(sh-heredoc ((((class color) (min-colors 89)) (:foreground "#CDC673" :weight bold))))
 '(sp-pair-overlay-face ((((class color) (min-colors 89)) (:background "#303030"))))
 '(sp-wrap-overlay-face ((((class color) (min-colors 89)) (:background "#303030"))))
 '(sp-wrap-tag-overlay-face ((((class color) (min-colors 89)) (:background "#303030"))))
 '(sp-show-pair-enclosing ((((class color) (min-colors 89)) (:inherit highlight))))
 '(sp-show-pair-match-face ((((class color) (min-colors 89)) (:foreground "#5FFFFF" :background "#1B1E1C" :weight normal :inverse-video t))))
 '(sp-show-pair-mismatch-face ((((class color) (min-colors 89)) (:foreground "#FF1493" :background "#1B1E1C" :weight normal :inverse-video t))))
 '(show-paren-match ((((class color) (min-colors 89)) (:foreground "#5FFFFF" :background "#1B1E1C" :weight normal :inverse-video t))))
 '(show-paren-mismatch ((((class color) (min-colors 89)) (:foreground "#FF1493" :background "#1B1E1C" :weight normal :inverse-video t))))
 '(paren-face-match ((((class color) (min-colors 89)) (:foreground "#5FFFFF" :background "#1B1E1C" :weight normal :inverse-video t))))
 '(paren-face-mismatch ((((class color) (min-colors 89)) (:foreground "#FF1493" :background "#1B1E1C" :weight normal :inverse-video t))))
 '(paren-face-no-match ((((class color) (min-colors 89)) (:foreground "#FF1493" :background "#1B1E1C" :weight normal :inverse-video t))))
 '(slime-repl-inputed-output-face ((((class color) (min-colors 89)) (:foreground "#FF1493"))))
 '(speedbar-button-face ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#8B8878"))))
 '(speedbar-directory-face ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#5FD7FF"))))
 '(speedbar-file-face ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#F5F5F5"))))
 '(speedbar-highlight-face ((((class color) (min-colors 89)) (:inherit variable-pitch :background "#303030"))))
 '(speedbar-selected-face ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#CDC673" :underline t))))
 '(speedbar-separator-face ((((class color) (min-colors 89)) (:inherit variable-pitch :background "#5FD7FF" :foreground "#1B1E1C" :overline "#AFEEEE"))))
 '(speedbar-tag-face ((((class color) (min-colors 89)) (:inherit variable-pitch :foreground "#87D700"))))
 '(sr-active-path-face ((((class color) (min-colors 89)) (:background "#5FD7FF" :foreground "#1B1E1C" :height 1.1 :weight bold))))
 '(sr-editing-path-face ((((class color) (min-colors 89)) (:background "#CDC673" :foreground "#1B1E1C" :weight bold :height 1.1))))
 '(sr-highlight-path-face ((((class color) (min-colors 89)) (:background "#87D700" :foreground "#1B1E1C" :weight bold :height 1.1))))
 '(sr-passive-path-face ((((class color) (min-colors 89)) (:background "#8B8878" :foreground "#1B1E1C" :weight bold :height 1.1))))
 '(sr-marked-dir-face ((((class color) (min-colors 89)) (:inherit dired-marked))))
 '(sr-marked-file-face ((((class color) (min-colors 89)) (:inherit dired-marked))))
 '(sr-alt-marked-dir-face ((((class color) (min-colors 89)) (:background "#D700D7" :foreground "#1B1E1C" :weight bold))))
 '(sr-alt-marked-file-face ((((class color) (min-colors 89)) (:background "#D700D7" :foreground "#1B1E1C" :weight bold))))
 '(sr-directory-face ((((class color) (min-colors 89)) (:inherit dired-directory :weight normal))))
 '(sr-symlink-directory-face ((((class color) (min-colors 89)) (:inherit dired-directory :slant italic :weight normal))))
 '(sr-symlink-face ((((class color) (min-colors 89)) (:inherit dired-symlink :slant italic :weight normal))))
 '(sr-broken-link-face ((((class color) (min-colors 89)) (:inherit dired-warning :slant italic :weight normal))))
 '(sr-compressed-face ((((class color) (min-colors 89)) (:foreground "#F5F5F5"))))
 '(sr-encrypted-face ((((class color) (min-colors 89)) (:foreground "#F5F5F5"))))
 '(sr-log-face ((((class color) (min-colors 89)) (:foreground "#F5F5F5"))))
 '(sr-packaged-face ((((class color) (min-colors 89)) (:foreground "#F5F5F5"))))
 '(sr-html-face ((((class color) (min-colors 89)) (:foreground "#F5F5F5"))))
 '(sr-xml-face ((((class color) (min-colors 89)) (:foreground "#F5F5F5"))))
 '(sr-clex-hotchar-face ((((class color) (min-colors 89)) (:background "#FF1493" :foreground "#1B1E1C" :weight bold))))
 '(table-cell ((((class color) (min-colors 89)) (:foreground "#F5F5F5" :background "#303030"))))
 '(term-color-black ((t (:foreground "#1B1E1C" :background "#303030"))))
 '(term-color-red ((t (:foreground "#FF1493" :background "#5F0000"))))
 '(term-color-green ((t (:foreground "#87D700" :background "#6B8E23"))))
 '(term-color-yellow ((t (:foreground "#CDC673" :background "#968B26"))))
 '(term-color-blue ((t (:foreground "#5FD7FF" :background "#21889B"))))
 '(term-color-magenta ((t (:foreground "#D700D7" :background "#A41F99"))))
 '(term-color-cyan ((t (:foreground "#5FFFFF" :background "#349B8D"))))
 '(term-color-white ((t (:foreground "#FFFAFA" :background "#F5F5F5"))))
 '(term-default-fg-color ((t (:inherit term-color-white))))
 '(term-default-bg-color ((t (:inherit term-color-black))))
 '(tooltip ((((class color) (min-colors 89)) (:background "#FFF68F" :foreground "#968B26" :inherit variable-pitch))))
 '(tuareg-font-lock-governing-face ((((class color) (min-colors 89)) (:foreground "#D700D7" :weight bold))))
 '(tuareg-font-lock-multistage-face ((((class color) (min-colors 89)) (:foreground "#5FD7FF" :background "#303030" :weight bold))))
 '(tuareg-font-lock-operator-face ((((class color) (min-colors 89)) (:foreground "#FFFAFA"))))
 '(tuareg-font-lock-error-face ((((class color) (min-colors 89)) (:foreground "#CDC673" :background "#FF1493" :weight bold))))
 '(tuareg-font-lock-interactive-output-face ((((class color) (min-colors 89)) (:foreground "#5FFFFF"))))
 '(tuareg-font-lock-interactive-error-face ((((class color) (min-colors 89)) (:foreground "#FF1493"))))
 '(undo-tree-visualizer-default-face ((((class color) (min-colors 89)) (:foreground "#8B8878" :background "#1B1E1C"))))
 '(undo-tree-visualizer-unmodified-face ((((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(undo-tree-visualizer-current-face ((((class color) (min-colors 89)) (:foreground "#5FD7FF" :inverse-video t))))
 '(undo-tree-visualizer-active-branch-face ((((class color) (min-colors 89)) (:foreground "#FFFAFA" :background "#1B1E1C" :weight bold))))
 '(undo-tree-visualizer-register-face ((((class color) (min-colors 89)) (:foreground "#CDC673"))))
 '(vhl/default-face ((((class color) (min-colors 89)) (:background "#B3EE3A" :foreground "#6B8E23"))))
 '(w3m-anchor ((((class color) (min-colors 89)) (:inherit link))))
 '(w3m-arrived-anchor ((((class color) (min-colors 89)) (:inherit link-visited))))
 '(w3m-form ((((class color) (min-colors 89)) (:background "#1B1E1C" :foreground "#F5F5F5"))))
 '(w3m-header-line-location-title ((((class color) (min-colors 89)) (:background "#303030" :foreground "#CDC673"))))
 '(w3m-header-line-location-content ((((class color) (min-colors 89)) (:background "#303030" :foreground "#F5F5F5"))))
 '(w3m-bold ((((class color) (min-colors 89)) (:foreground "#FFFAFA" :weight bold))))
 '(w3m-image-anchor ((((class color) (min-colors 89)) (:background "#1B1E1C" :foreground "#5FFFFF" :inherit link))))
 '(w3m-image ((((class color) (min-colors 89)) (:background "#1B1E1C" :foreground "#5FFFFF"))))
 '(w3m-lnum-minibuffer-prompt ((((class color) (min-colors 89)) (:foreground "#FFFAFA"))))
 '(w3m-lnum-match ((((class color) (min-colors 89)) (:background "#303030"))))
 '(w3m-lnum ((((class color) (min-colors 89)) (:underline nil :bold nil :foreground "#FF1493"))))
 '(w3m-session-select ((((class color) (min-colors 89)) (:foreground "#F5F5F5"))))
 '(w3m-session-selected ((((class color) (min-colors 89)) (:foreground "#FFFAFA" :bold t :underline t))))
 '(w3m-tab-background ((((class color) (min-colors 89)) (:background "#1B1E1C" :foreground "#F5F5F5"))))
 '(w3m-tab-selected-background ((((class color) (min-colors 89)) (:background "#1B1E1C" :foreground "#F5F5F5"))))
 '(w3m-tab-mouse ((((class color) (min-colors 89)) (:background "#303030" :foreground "#CDC673"))))
 '(w3m-tab-selected ((((class color) (min-colors 89)) (:background "#303030" :foreground "#FFFAFA" :bold t))))
 '(w3m-tab-unselected ((((class color) (min-colors 89)) (:background "#303030" :foreground "#F5F5F5"))))
 '(w3m-tab-selected-retrieving ((((class color) (min-colors 89)) (:background "#303030" :foreground "#FF1493"))))
 '(w3m-tab-unselected-retrieving ((((class color) (min-colors 89)) (:background "#303030" :foreground "#FF8C00"))))
 '(w3m-tab-unselected-unseen ((((class color) (min-colors 89)) (:background "#303030" :foreground "#AF87FF"))))
 '(web-mode-builtin-face ((((class color) (min-colors 89)) (:foreground "#FF1493"))))
 '(web-mode-comment-face ((((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(web-mode-constant-face ((((class color) (min-colors 89)) (:foreground "#5FD7FF" :weight bold))))
 '(web-mode-current-element-highlight-face ((((class color) (min-colors 89)) (:underline unspecified :weight unspecified :background "#303030"))))
 '(web-mode-css-at-rule-face ((((class color) (min-colors 89)) (:foreground "#AF87FF" :slant italic))))
 '(web-mode-css-pseudo-class-face ((((class color) (min-colors 89)) (:foreground "#87D700" :slant italic))))
 '(web-mode-doctype-face ((((class color) (min-colors 89)) (:foreground "#8B8878" :slant italic :weight bold))))
 '(web-mode-folded-face ((((class color) (min-colors 89)) (:underline t))))
 '(web-mode-function-name-face ((((class color) (min-colors 89)) (:foreground "#5FD7FF"))))
 '(web-mode-html-attr-name-face ((((class color) (min-colors 89)) (:foreground "#5FD7FF" :slant normal))))
 '(web-mode-html-attr-value-face ((((class color) (min-colors 89)) (:foreground "#5FFFFF" :slant italic))))
 '(web-mode-html-tag-face ((((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(web-mode-keyword-face ((((class color) (min-colors 89)) (:foreground "#CDC673" :weight normal))))
 '(web-mode-preprocessor-face ((((class color) (min-colors 89)) (:foreground "#CDC673" :slant normal :weight unspecified))))
 '(web-mode-string-face ((((class color) (min-colors 89)) (:foreground "#5FFFFF"))))
 '(web-mode-type-face ((((class color) (min-colors 89)) (:foreground "#CDC673"))))
 '(web-mode-variable-name-face ((((class color) (min-colors 89)) (:foreground "#5FD7FF"))))
 '(web-mode-warning-face ((((class color) (min-colors 89)) (:inherit font-lock-warning-face))))
 '(web-mode-block-attr-name-face ((((class color) (min-colors 89)) (:inherit web-mode-html-attr-name-face))))
 '(web-mode-block-attr-value-face ((((class color) (min-colors 89)) (:inherit web-mode-html-attr-value-face))))
 '(web-mode-block-comment-face ((((class color) (min-colors 89)) (:inherit web-mode-comment-face))))
 '(web-mode-block-control-face ((((class color) (min-colors 89)) (:inherit font-lock-preprocessor-face))))
 '(web-mode-block-face ((((class color) (min-colors 89)) (:background unspecified))))
 '(web-mode-block-string-face ((((class color) (min-colors 89)) (:inherit web-mode-string-face))))
 '(web-mode-comment-keyword-face ((((class color) (min-colors 89)) (:box 1 :weight bold))))
 '(web-mode-css-color-face ((((class color) (min-colors 89)) (:inherit font-lock-builtin-face))))
 '(web-mode-css-function-face ((((class color) (min-colors 89)) (:inherit font-lock-builtin-face))))
 '(web-mode-css-priority-face ((((class color) (min-colors 89)) (:inherit font-lock-builtin-face))))
 '(web-mode-css-property-name-face ((((class color) (min-colors 89)) (:inherit font-lock-variable-name-face))))
 '(web-mode-css-selector-face ((((class color) (min-colors 89)) (:inherit font-lock-keyword-face))))
 '(web-mode-css-string-face ((((class color) (min-colors 89)) (:inherit web-mode-string-face))))
 '(web-mode-javascript-string-face ((((class color) (min-colors 89)) (:inherit web-mode-string-face))))
 '(web-mode-json-context-face ((((class color) (min-colors 89)) (:foreground "#AF87FF"))))
 '(web-mode-json-key-face ((((class color) (min-colors 89)) (:foreground "#AF87FF"))))
 '(web-mode-json-string-face ((((class color) (min-colors 89)) (:inherit web-mode-string-face))))
 '(web-mode-param-name-face ((((class color) (min-colors 89)) (:foreground "#F5F5F5"))))
 '(web-mode-part-comment-face ((((class color) (min-colors 89)) (:inherit web-mode-comment-face))))
 '(web-mode-part-face ((((class color) (min-colors 89)) (:inherit web-mode-block-face))))
 '(web-mode-part-string-face ((((class color) (min-colors 89)) (:inherit web-mode-string-face))))
 '(web-mode-symbol-face ((((class color) (min-colors 89)) (:foreground "#CDC673"))))
 '(web-mode-whitespace-face ((((class color) (min-colors 89)) (:background "#FF1493"))))
 '(whitespace-space ((((class color) (min-colors 89)) (:background unspecified :foreground "#8B8878" :inverse-video unspecified :slant italic))))
 '(whitespace-hspace ((((class color) (min-colors 89)) (:background unspecified :foreground "#FFFAFA" :inverse-video unspecified))))
 '(whitespace-tab ((((class color) (min-colors 89)) (:background unspecified :foreground "#FF1493" :inverse-video unspecified :weight bold))))
 '(whitespace-newline ((((class color) (min-colors 89)) (:background unspecified :foreground "#8B8878" :inverse-video unspecified))))
 '(whitespace-trailing ((((class color) (min-colors 89)) (:background unspecified :foreground "#FFA54F" :inverse-video t))))
 '(whitespace-line ((((class color) (min-colors 89)) (:background unspecified :foreground "#D700D7" :inverse-video unspecified))))
 '(whitespace-space-before-tab ((((class color) (min-colors 89)) (:background "#EE6AA7" :foreground unspecified :inverse-video unspecified))))
 '(whitespace-indentation ((((class color) (min-colors 89)) (:background unspecified :foreground "#CDC673" :inverse-video unspecified :weight bold))))
 '(whitespace-empty ((((class color) (min-colors 89)) (:background unspecified :foreground "#EE6AA7" :inverse-video t))))
 '(whitespace-space-after-tab ((((class color) (min-colors 89)) (:background unspecified :foreground "#FF8C00" :inverse-video t :weight bold))))
 '(wl-highlight-folder-few-face ((((class color) (min-colors 89)) (:foreground "#FF1493"))))
 '(wl-highlight-folder-many-face ((((class color) (min-colors 89)) (:foreground "#FF1493"))))
 '(wl-highlight-folder-path-face ((((class color) (min-colors 89)) (:foreground "#FF8C00"))))
 '(wl-highlight-folder-unread-face ((((class color) (min-colors 89)) (:foreground "#5FD7FF"))))
 '(wl-highlight-folder-zero-face ((((class color) (min-colors 89)) (:foreground "#F5F5F5"))))
 '(wl-highlight-folder-unknown-face ((((class color) (min-colors 89)) (:foreground "#5FD7FF"))))
 '(wl-highlight-message-citation-header ((((class color) (min-colors 89)) (:foreground "#FF1493"))))
 '(wl-highlight-message-cited-text-1 ((((class color) (min-colors 89)) (:foreground "#FF1493"))))
 '(wl-highlight-message-cited-text-2 ((((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(wl-highlight-message-cited-text-3 ((((class color) (min-colors 89)) (:foreground "#5FD7FF"))))
 '(wl-highlight-message-cited-text-4 ((((class color) (min-colors 89)) (:foreground "#5FD7FF"))))
 '(wl-highlight-message-header-contents-face ((((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(wl-highlight-message-headers-face ((((class color) (min-colors 89)) (:foreground "#FF1493"))))
 '(wl-highlight-message-important-header-contents ((((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(wl-highlight-message-header-contents ((((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(wl-highlight-message-important-header-contents2 ((((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(wl-highlight-message-signature ((((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(wl-highlight-message-unimportant-header-contents ((((class color) (min-colors 89)) (:foreground "#F5F5F5"))))
 '(wl-highlight-summary-answered-face ((((class color) (min-colors 89)) (:foreground "#5FD7FF"))))
 '(wl-highlight-summary-disposed-face ((((class color) (min-colors 89)) (:foreground "#F5F5F5" :slant italic))))
 '(wl-highlight-summary-new-face ((((class color) (min-colors 89)) (:foreground "#5FD7FF"))))
 '(wl-highlight-summary-normal-face ((((class color) (min-colors 89)) (:foreground "#F5F5F5"))))
 '(wl-highlight-summary-thread-top-face ((((class color) (min-colors 89)) (:foreground "#CDC673"))))
 '(wl-highlight-thread-indent-face ((((class color) (min-colors 89)) (:foreground "#D700D7"))))
 '(wl-highlight-summary-refiled-face ((((class color) (min-colors 89)) (:foreground "#F5F5F5"))))
 '(wl-highlight-summary-displaying-face ((((class color) (min-colors 89)) (:underline t :weight bold))))
 '(weechat-error-face ((((class color) (min-colors 89)) (:inherit error))))
 '(weechat-highlight-face ((((class color) (min-colors 89)) (:foreground "#FFFAFA" :weight bold))))
 '(weechat-nick-self-face ((((class color) (min-colors 89)) (:foreground "#87D700" :weight unspecified :inverse-video t))))
 '(weechat-prompt-face ((((class color) (min-colors 89)) (:inherit minibuffer-prompt))))
 '(weechat-time-face ((((class color) (min-colors 89)) (:foreground "#8B8878"))))
 '(which-func ((((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(window-number-face ((((class color) (min-colors 89)) (:foreground "#87D700"))))
 '(yascroll:thumb-text-area ((((class color) (min-colors 89)) (:foreground "#8B8878" :background "#8B8878"))))
 '(yascroll:thumb-fringe ((((class color) (min-colors 89)) (:foreground "#8B8878" :background "#8B8878"))))
 '(zencoding-preview-input ((((class color) (min-colors 89)) (:background "#303030" :box "#FFFAFA"))))
 '(default ((t (:background "undefined-bg" :foreground "#F5F5F5")))))

(provide-theme 'monokai)
